### ISSUE TITLE
Give ID results unique hyperlinks

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#100]
In the iNat guide system, if you select a set of criteria, it generates a unique hyperlink. EG [this is the set of integral galls on Carya ovata with thick walls](https://www.inaturalist.org/guides/12068?tags%5B%5D=Detachable%3Dno&tags%5B%5D=Carya%3Dovata&tags%5B%5D=walls%3Dthick). So if you click through to a gall, then click back, it returns you to your search results. Is it possible to alter our ID tool to behave this way, rather than the way it does now (always have to start from scratch)? This feature also allows you to link to relevant search results in conversations on iNat, etc.

**Comment by jeffdc** [comment]
Yes we can make this work. This is all client side work (no DB etc.). 

Quick thoughts on implementation:

* Add the ID criteria as query parameters
* Modify the getServerSideProps() call to accept the context (see e.g., any of the admin pages)
* Extract the query params and fetch the data and pass it to the page as props:
    * filtered - current React state that holds the list of filtered galls by host
    * SearchQuery - how the galls are filtered on the page - see doSearch() in the id.tsx page
* import the next.js router - see any of the admin pages - and update it with shallow navigations to reflect changes to filter criteria as the user makes selections
