### ISSUE TITLE
Dropdown menus in Add Gall reopen instantaneously when clicking below them

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#101]
On the Add/Edit Gallformers page, if I click either the Hosts or Locations field, select my first option, then click anywhere below the field, eg to add a detachable entry or to submit the gall, anywhere in the space where the dropdown menu was, it acts as if the menu were still there and lets me select another entry.

It's not hugely annoying but another thing that could lead to erroneous data being entered if users aren't paying attention to it.

**Comment by jeffdc** [comment]
I can not replicate this one. If it still fails for you it could be an OS/Browser difference. What OS & Browser are you using?

**Comment by Megachile** [comment]
I'm running Windows 10 home 64 bit and using Firefox at the moment. I'll check chrome and edge and see if it makes a difference.

**Comment by jeffdc** [comment]
I have tried it on Chrome and Firefox on Mac OS and do not see it. Maybe I am not understanding the issue. Can you create a screen recording and post it here?

**Comment by Megachile** [comment]
Well of course it's not happening now in Edge or Firefox. Maybe it got fixed in some other alterations you made. If it happens again I'll record and reopen the issue.

**Comment by jeffdc** [comment]
It is quite possible, though that is really odd behavior.

**Comment by Megachile** [comment]
Finally got a video of this. It happens when I'm using the map-host-gall page as well, and what seems to trigger it reliably is when I enter a couple of options, click to another window, then come back in to hit submit without interacting with the window any other way first.
https://user-images.githubusercontent.com/69063635/115948866-b5fd5a80-a49e-11eb-8594-41d68978fc18.mp4

**Comment by jeffdc** [comment]
Ahh I see it now. On my machine when I leave the page with the cursor in the selection box then come back the selection list is expanded. For you it is hidden until you click (which rather poor behavior on its part!). I will see what I can do. This is a 3rd party open source component that I am using so it might be a tough one to fix.

**Comment by Megachile** [comment]
It's not a big deal, especially now that I'm aware of how to avoid it. But could cause issues for new users.
