### ISSUE TITLE
Make Family, Section, and Genus pages appear in global search results

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#103]
At the moment, our global search feature only lists Sources and either Host or Gall "species" results, because these are the only entries in the db that have corresponding pages to link to. For instance, if you search "Quercus" you'll get the species page for every host in that genus, but no page for the genus itself. Since we can already handle searching for every gall on a genus using the ID tool (replacing the [genus-level gall table on Bladmineerders](https://bladmineerders.nl/host-plants/plantae/spermatopsida/angiosperma/eudicots/superrosids/rosids/fabids/fagales/fagaceae/quercus/genus-quercus/), which I use all the time), it's not clear how much utility having a genus (or section, or family) page would necessarily add. 

But it is something I expected to be able to do, and which I think other users will expect to be able to do. Is it worth the effort to add this? If so, what should be displayed on these pages?

**Comment by Megachile** [comment]
@jeffdc I'm slightly confused by what you told me last time we talked about this, because families do literally have pages already. Is there a reason we can't just link to this page eg if I search "[Fagaceae](https://www.gallformers.org/family/15)" ? I just find it weird somehow that we can have hundreds of plants added in a family but the search tool acts as if it doesn't exist. I've been using the search tool to check the presence of different taxa and aliases etc to see what needs to be added and if these higher taxa don't show in search then that isn't possible.

**Comment by jeffdc** [comment]
You are correct that we have family pages, I forgot about those. We could also create Section pages. There is no reason we can not add this stuff to global search.

**Comment by jeffdc** [comment]
@megachile here is what I came up with:

Search results:
![Screen Shot 2021-04-22 at 11 22 33 AM](https://user-images.githubusercontent.com/39919/115741161-7ed36000-a35d-11eb-8367-4239bf781f39.png)

New Genus Page:
![Screen Shot 2021-04-22 at 11 22 54 AM](https://user-images.githubusercontent.com/39919/115741195-85fa6e00-a35d-11eb-97f2-e9733fb25239.png)

Gall Page:
![Screen Shot 2021-04-22 at 11 25 33 AM](https://user-images.githubusercontent.com/39919/115741251-90b50300-a35d-11eb-930b-03c8a0a171e3.png)

Host Page:
![Screen Shot 2021-04-22 at 11 23 24 AM](https://user-images.githubusercontent.com/39919/115741274-97437a80-a35d-11eb-9925-f7c713eb8fca.png)

**Comment by Megachile** [comment]
Looks good to me. I have definitely found myself wishing for a link to all the galls in a genus on gall page too, so that will be good to have.
