### ISSUE TITLE
Add completion tracker for sources

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#107]
I have for the most part been adding source info by gall so far, but it has occurred to me that it at some point it might become easier to find overlooked info if we went through known sources systematically instead. Eg, say a species was not read properly into BHL's OCR, which happens not infrequently. That means you can't search for entries associated with that species. If it's an original description, you can find it by consulting one of the Weld books or the Amrine catalog etc, but sometimes later descriptions are more informative and simply wouldn't be findable by this method. Some are just not things we'll find unless we get really lucky, but most are actually included in the same sources we already have added to the db. If we went through them systematically we'd find these missing entries. 

To facilitate that, it would be nice if we had a check box associated with sources to mark which ones had been completely added to the db, similar to the DQI boxes. Doesn't need to be publicly viewable but could be, since there's no easy way to display this info in bulk on the admin side. Or we could make a tool that displayed a full list of "unfinished" sources in general--an especially useful possibility if we get volunteers interested in helping with  transcribing but not comfortable looking for sources etc.

**Comment by Megachile** [comment]
It might also make sense to add a list of galls associated with a source somewhere too?

**Comment by jeffdc** [comment]
I am only going to add a complete flag for Source. Adding gall-source mapping is a much greater level of complexity and I do not think that we need it if its only purpose is to track completion. If we feel we really need it, break it out into a new issue.

**Comment by Megachile** [comment]
That sounds good. To be clear, what I had in mind was basically like what is currently displayed on the page for each host, just a list of all the galls with a mapping to that source. But yeah, that is a different thing.

**Comment by jeffdc** [comment]
@Megachile can you please open (a) new issue(s) for:

- mapping galls to sources if you think that we need it
- providing search/reporting on incomplete sources, galls, hosts
