### ISSUE TITLE
Automatically link to gall pages?

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#109]
This is another "nice to have" idea to think about in the long term that might have implications today.

As I write our "ID Notes" for various species, I'm obviously referencing the names of other species I compare them to. It would be convenient if the site could automatically hyperlink those to the appropriate gall pages, in the same way it automatically links terms in the glossary. If that is a feature we might someday add, we should adopt on a policy of never using abbreviations for species names, because eg "N q batatus" would presumably not trigger an automatic link code for Neuroterus quercusbatatus.

**Comment by jeffdc** [comment]
I think that this would be an awesome feature. Most of the code is already in place to make it happen. However, I do wonder about performance issues. The glossary is not very large so lookups are quick when marking up text for words. The number of species is going to be much larger (already is) and may lead to performance issues. There are probably ways around this, but a naive approach may cause issues.

**Comment by Megachile** [comment]
Okay well if you think it's something we could maybe do later then I think it's worth planning for it now by always using the full names of each species where relevant.
