### ISSUE TITLE
Alias tool in Add Galls is wonky

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#110]
The Alias editor in Add/Edit Galls works, but it has some weird and kind of annoying behaviors. Any alias that was added previously seems stable, but if I am trying to add multiple new aliases at once, it gets weird. It adds a new row each time I click "Add Alias," but it's almost like it's treating them as the same entry. If I select one with the check box, all of the new ones are selected. If I enter a name in one field, move to the next one and write a new name, then click back into the first, it pastes the second name over the first. I'm also seeing aliases persist after I delete them, and being undeletable at that point. 

Clicking submit between each new alias seems to prevent the issue, so it's totally usable if you do that.

**Comment by jeffdc** [comment]
I will fix this and get it in with the current PR that I am working on: #108

**Comment by jeffdc** [comment]
Can you point me to the species that has the undeletable aliases? I fixed the other problem, was an easy one.

**Comment by Megachile** [comment]
That was also something that was fixed by submitting/refreshing the page, I doubt it's a separate problem.

**Comment by jeffdc** [comment]
Ok cool.
