### ISSUE TITLE
Link from Add Gall to Gall page

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#111]
Before the latest deployment, the confirmation text when you submitted edits to a gall or made a new one included a link to the gall page. That seems to be gone now--is it something we could add in some form? And/or a direct link to map sources for the gall, like the "Add/Edit Images" is now?

**Comment by Megachile** [comment]
It would also be nice to have a link back from the map sources to the gall page.

**Comment by jeffdc** [comment]
Will add these links, easy to do.

**Comment by jeffdc** [comment]
Will be in next deployment.
