### ISSUE TITLE
Add New Mapped Source doesn't match active title

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#112]
This is a borderline non-problem but potentially confusing if you're not aware of it.

If you click "Add New Mapped Source" and enter a new source, then type your Description and submit, it correctly associates with the newly added source. No problem. But the title in the Mapped Source field doesn't update to match that unless you click through and select it, so I kept panicking at first thinking I had missed a step and overwritten existing data (I think it defaults to show the earliest source).

**Comment by jeffdc** [comment]
Should be an easy fix.

**Comment by Megachile** [comment]
In case it's useful, this doesn't seem to happen when there is only one source. If I add a second source for a gall, the Mapped Source field changes to the newly added title as it should.

**Comment by jeffdc** [comment]
Fixed in next deployment.
