### ISSUE TITLE
Proposed filter terms to add

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#115]
Walls:

Spongy 
Radiating fibers

Cells: 
Free-rolling

Textures:
Mottled
Succulent

**Comment by Megachile** [comment]
Textures:
Leafy

**Comment by Megachile** [comment]
Textures: 
Spiky/Thorny

**Comment by Megachile** [comment]
All of them are in there except spongy

**Comment by jeffdc** [comment]
Fixed.
