### ISSUE TITLE
Display DQIs on ID Results 

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#116]
Idk how useful this would be for users--potentially somewhat useful--but I think it would be nice as an admin to be able to pull up a list of eg all the stem galls on a particular host and check if they had all been completed yet. Displaying the icon on the ID search results would be an easy way to track that progress and find gaps that need to be filled.

**Comment by jeffdc** [comment]
I added the edit pencil and the completion status to the ID results. This is visible only to a logged in Admin.
![Screen Shot 2021-05-19 at 11 12 33 AM](https://user-images.githubusercontent.com/39919/118837956-460ea400-b893-11eb-85ed-b9ae9eb05c2c.png)

**Comment by Megachile** [comment]
Awesome, thank you
