### ISSUE TITLE
Add/Edit Species Images not working

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#118]
The Species field on the add images page shows the normal dropdown menu and searches as I enter letters, but if I select a species, the dropdown closes but no species is selected, no images appear, and the add image button doesn't appear.

**Comment by Megachile** [comment]
The page does work if I navigate to a specific gall's images using the edit link from a gall page, though of course that link only appears for species that have an image added already.

**Comment by jeffdc** [comment]
Will be fixed in next deployment.
