### ISSUE TITLE
Add confirmation modal before major changes

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#119]
At the moment, it is relatively easy to accidentally destroy information, either by deleting or overwriting it. Should we add a confirmation box so that users are alerted before making changes like this, before they delete a gall that may have substantial amounts of information associated with it (eg by checking the delete box when they meant to check the undescribed box), or before they overwrite existing information (eg using the copy tool in the Add Images page)?

**Comment by jeffdc** [comment]
I think it makes sense. I was actually thinking of changing delete to be a separate button as well.
