### ISSUE TITLE
Mapped Source dropdown only shows oldest source

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#120]
Trying to edit a typo in the ID Notes for A confluenta but the Map Species page only shows the oldest source in the dropdown menu, can't select any other mapped sources. Same thing happens if I go through the link on the Gall page or through the admin menu to get there.

**Comment by jeffdc** [comment]
It is a bit of a UI quirk, all you have to do is clear the current selection (use the X on the right) and then you can select anything. It is using the same typeahead control as all of the other fields. It was a dropdown but that created problems, both in implementation and usability.
