### ISSUE TITLE
Family field in Add Gall not working

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#123]
The Family field is auto-filling known genera (yay!) but won't let me associate a family with a new genus (which of course also means I can't submit the gall at all). It won't let me type more than a letter in and it empties if I select any option. Video attached. 

https://user-images.githubusercontent.com/69063635/114770016-f0495800-9d38-11eb-9a85-d76c926dd183.mp4

**Comment by jeffdc** [comment]
Will fix this with the other and get them deployed today barring some roadblock.
