### ISSUE TITLE
Selecting any other field clears Detachable

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#124]
Selecting or clearing a host, walls, location, color, etc clears any selection previously made in Detachable, unless the detachable field has previously been submitted. 

https://user-images.githubusercontent.com/69063635/114822822-a2603e80-9d90-11eb-9b46-a781b9e6858c.mp4

**Comment by Megachile** [comment]
This is happening again

**Comment by jeffdc** [comment]
Sigh. I tested this one over and over again. :( I can not umderstand why this field is special and fragile! Will look at it
