### ISSUE TITLE
Filter fields not clearing or applying when host is changed

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#129]
Eg if I search Quercus lyrata, apply the "fruit" location, then switch to Quercus alba, "fruit" remains displayed in the field but all galls for Q alba are displayed, as if nothing were selected. Personally I'd prefer it if the site did retain these filters when you changed hosts (IE if I input a bunch of filters, then change host, I don't want to have to input them all again) but if so, they should behave as if they're active.

**Comment by jeffdc** [comment]
AS part of #100 I am fixing this. However the behavior will not be as you describe. I messed around with it a bunch and I think that the only way to handle this without baffling the user is for it to work like this:

- If you navigate to the ID page from any link within the site, you get an empty page like now
- I have removed the 'Search' button and the search will be executed immediately once a valid selection is made in either the Host or Genus box
- Selecting any of the filter criteria will execute an immediate search, just like it does now
- The URL will be updated for every change that the user makes to any of the search page input boxes. This means that the URL will exactly match what is displayed on the screen at all time and can be copied and shared
- If you navigate to the page via a shared URL with search params, the page will load with the correct galls and the search params pre-filled
- If the user changes the Host/Genus, the filter criteria will NOT clear but the galls will be filtered correctly
- I have added a Reset Form button that will clear all selections and present the empty ID page

@megachile what do you think about this?

**Comment by Megachile** [comment]
I'm not sure how that differs from what I said but it sounds great to me.

**Comment by jeffdc** [comment]
🤣 I mis-read "Personally I'd prefer it if the site did retain these filters..." as "Personally I'd prefer it if the site did **not** retain these filters..."
