### ISSUE TITLE
Add seasons filter

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#133]
Per discussion in #56, let's add a season filter to the ID page, and a multiselect field to the Add Galls page, with Spring, Summer, Fall, and Winter as the options. 

This will be accompanied by a new bullet in the ID Troubleshooting Tips:

- wrong season selected. Galls often persist long after their season of appearance. Only use this filter if the gall is obviously fresh.

**Comment by jeffdc** [comment]
This would also be under the new "advanced filters" fold?

**Comment by Megachile** [comment]
That's what I had in mind based on our discussion in #56, yeah. But of course open to further discussion at this point.
