### ISSUE TITLE
Copy metadata copying to images that aren't selected

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#143]
I've just added four images to Aceria celtis. If I select one to copy and use the copy tool to select my paste target, it also pastes to a different observation I haven't selected. It seems to have stopped doing it after I refreshed the page.

**Comment by jeffdc** [comment]
I have been able to, intermittently replicate this one. It is very weird. I have not yet gotten it down to a repeatable set of steps. This is a bad one as it destroys data. I am sorry.

**Comment by jeffdc** [comment]
I *think* that I know why it was happening. If you were on species A made some selections and/or copies, then switched to species B without leaving the page, it would carry the previous selection info over. I now make sure to clear out all intermediate data when the species is switched. It seems to have fixed it as I can no longer get it to start acting weird.

**Comment by Megachile** [comment]
I'm glad you were able to reproduce it--it was so ephemeral I worried it wouldn't be possible. But it does seem like a good thing to have fixed. Thanks!
