### ISSUE TITLE
How to display incomplete/complete sources, galls, and hosts?

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#148]
Now that sources, galls, and hosts all have DQIs indicating their status, it would be useful to at least be able to see them listed somewhere, if not to search them somehow. I'm not certain how best to achieve this. #116 seems like a reasonable solution for galls, allowing us to search by host. But it might also be good to have them shown on the explore page, so you could browse by taxon for both hosts and inducers. 

If that seems like a good and sufficient solution for galls and hosts, we'd just need to figure out a way to display completeness for Sources. At the moment, there is no way to view a list of sources at all. Perhaps we could just make a big table that allows you to sort by completeness status? I can't think of an obvious good alternative. Eg you might want to see only sources related to galls on a particular host, or sources related to galls in a particular taxon, etc, but I'm not sure the query infrastructure to do that would be worth the effort to build.

**Comment by jeffdc** [comment]
This is not the prettiest but does this work?

![Screen Shot 2021-04-23 at 12 04 34 PM](https://user-images.githubusercontent.com/39919/115898925-2323d800-a42c-11eb-94ff-a4079f160c18.png)

**Comment by jeffdc** [comment]
Then I will add a way to filter these results by completion status.

**Comment by Megachile** [comment]
I'm not convinced this list should have expansions to show the species at all? You can just click through to the source page to see that list. Otherwise yeah this seems fine. Would also be convenient to me right now to sort by copyright just so I can find the ones that are missing this info, but that's not crucial and maybe not at all useful in the long run.

**Comment by jeffdc** [comment]
Yep I can eliminate the species easily. I will move it to a table so there are more sorting options.

**Comment by jeffdc** [comment]
![Screen Shot 2021-04-23 at 9 51 14 PM](https://user-images.githubusercontent.com/39919/115943456-13cd7a80-a47e-11eb-8597-d767aa634408.png)

**Comment by jeffdc** [comment]
Another idea is to have this in the admin area and have the cells be editable. This would be good for quick changes. I have not done much with this table and editing (only the species aliases) but it is something that we could think about adding.

**Comment by Megachile** [comment]
That table looks good. I don't see a reason to make the cells editable personally, but it's fine if you want to. Source editing doesn't happen much in my experience.

**Comment by jeffdc** [comment]
Should this be public facing or should it be admin only? I can create similar tables for hosts and galls.

**Comment by Megachile** [comment]
I was thinking it would be good to make the gall/host lists public-facing in the first place so I guess why not make them all that way.

**Comment by Megachile** [comment]
From an admin perspective, if we're making such a table for galls, it would be useful if it displayed other traits too. Obviously the db can't tell us whether it's complete, but it would eg be nice to be able to find galls missing values for season, shape, whatever. Idk how filterable such a table could be though. What I'm imagining now would be closer to a table view of the results of the ID tool which is maybe out of scope for this discussion.

**Comment by jeffdc** [comment]
I am going to start with these tables being Admin only. They are heavy because they are exposing large sets of data. I have already noticed that the site is getting slower. This is due mainly to the fact that the $5 month server is getting bogged down.

**Comment by jeffdc** [comment]
I think that we need to have a larger discussion about this. I am going to put in simple versions of these tables, accessible to admins only, for now. 

What I think you are really after is a much more complicated thing, as you eluded to above and in #159.

**Comment by Megachile** [comment]
Sounds good. At this point it's a convenience for us in terms of tracking progress more than anything.
