### ISSUE TITLE
Source/Species Mapping Allows Multiple Entries per Source

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#152]
I just added a [second mapping](https://www.gallformers.org/gall/594) for Weld when that source already had an entry for the species. I didn't check before I used the Add New Mapped Source tool because I didn't think the site would let me select one that was already mapped, but apparently it did. The gall page doesn't seem to really know how to handle it--selecting either highlights both and displays the older text. But the new text is still saved in the database.

I'm not sure what if any harm this is doing to the database since it's not really designed for this outcome, but it seems like it would be best to just make it impossible on the mapping page?

**Comment by jeffdc** [comment]
Yeah that is not good. I will fix it and clean up the data
