### ISSUE TITLE
Should we have a better way to link iNat/BG observations?

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#153]
I often find myself wanting to connect our gall pages to either a single or several observations on iNat, especially for undescribed species that can't just be found through the existing search links. Ideally this would be a way to collect all known observations in one place.

The only way to do this at the moment is to paste the URLs into our ID Notes, [as I've done here](https://www.gallformers.org/gall/1058). This is inconvenient to return to in the future because URLs in source-gall mappings are not hyperlinked, plus it just looks janky.  Linking to a [Similar Observation Set as I've done here](https://www.gallformers.org/gall/1101) limits the problem to one link but that isn't worthwhile for cases where there are more than one but still only a few observations. It occurred to me that we could use the images page for this, which already has a field for inat/bg links, but I don't like that idea (in part because the images are often too bad to use otherwise, in part because it would often be more images than I'd otherwise use). 

Possible solutions:

1. Leave as is. Not worth the effort of changing anything.
2. Enable the species-source description field to parse URLs automatically. 
3. Create a dedicated page/field for entering and displaying links of this sort, with a new place on the gall page to display them (TBD what that would look like)

**Comment by jeffdc** [comment]
Option 2 is probably not very hard and buys us a lot. One thing I was thinking about for that description field is to support Markdown. This would give us links as well as formatting. I do not know how complicated this would be though.

**Comment by jeffdc** [comment]
Here is a markdown component that I could try and integrate: https://remarkjs.github.io/react-markdown/

**Comment by Megachile** [comment]
Do you imagine implementing that with a WYSIWYG for the editor? I don't think we can ask users to actually code their formatting.

**Comment by jeffdc** [comment]
Markdown is very easy and the minimum we want is stuff like links and maybe some header formatting etc. If folks can not do that, then... well I don't know. It is the same as this editor here on GitHub. We could add a toolbar to make things easier but No WYSWIG. 

The hitch with this is that we also want to have auto linking of glossary terms (and eventually species). Things can get messy real fast when they are combined (the auto-linking and the markdown parsing).

**Comment by jeffdc** [comment]
Github actually has an extension of Markdown that allows referring to issues with the `#153` for #153 syntax. The component I linked has the ability add custom plugins for parsing so we could eliminate the auto-linking as it is now, and instead do it with some kind of custom syntax for terms, species, etc.

**Comment by jeffdc** [comment]
If I am not making sense, let me know. We could hop on a call or something and I could explain.

**Comment by jeffdc** [comment]
I just hacked that component in to see what it is like:

![Screen Shot 2021-04-22 at 8 49 34 PM](https://user-images.githubusercontent.com/39919/115802119-44dd7a80-a3ac-11eb-8f60-f7558132af85.png)
![Screen Shot 2021-04-22 at 8 49 26 PM](https://user-images.githubusercontent.com/39919/115802121-45761100-a3ac-11eb-85fc-1310c5484edf.png)
![Screen Shot 2021-04-22 at 8 49 06 PM](https://user-images.githubusercontent.com/39919/115802122-460ea780-a3ac-11eb-8944-c85ca5a31a12.png)

**Comment by jeffdc** [comment]
Next step would be to figure out hard it is to do custom parsing for the glossary and potentially species as well.

**Comment by jeffdc** [comment]
This looks like a way to handle the glossary: https://github.com/freesewing/freesewing/tree/develop/packages/remark-jargon

**Comment by Megachile** [comment]
Oh no sorry I think the github version is fine, I was thinking of the React code on the left side of [this link you shared](https://remarkjs.github.io/react-markdown/). 

If you think we can have both the glossary and this formatting that's great.

**Comment by jeffdc** [comment]
The left side is not React code but complex Markdown. That example is using a lot of plugins etc. so it looks complicated. We would do the basics like what is here on GH or on iNat.

 Glossary and formatting looks like a definite yes. Linking to species is not as straight-forward. I really want to provide that but it is not straight-forward, one of the downsides of not using the species names in the URLs (which has its own huge set of problems!).

**Comment by Megachile** [comment]
Linking to species is something that would be nice to have but not ultimately necessary--you can always paste the name into search.

**Comment by jeffdc** [comment]
I have figured out an approach where we can get the linking that we want. When the description is changed I can either add a button so that the user can have the system edit the text to insert all the correct highlighting/linking before they save, or it can happen automatically on save. 

This is good because it means the system no longer has to compute the links at runtime which is a big reduction in complexity and resource usage. 

The major downside is that if stuff changes the links will grow stale. e.g., if a term is changed/deleted (the name not the definition) any description that was linked to it will no longer be accurate.

**Comment by jeffdc** [comment]
Currently the glossary linker is "smart" and can link based on word stems. This means that a term like "galling" would get linked since the stem, "gall", is in the glossary. Do we want to carry this functionality forward?

**Comment by Megachile** [comment]
Maybe if we're reevaluating our glossary anyway, this would be a good time to look into integrating Andy's [Terminology spreadsheet ](https://scholarsphere.psu.edu/resources/c4f9dca9-7830-411b-9b7a-e3b84bef059a) somehow? Each of his terms has a definition in the spreadsheet but many also link to a website. Not sure if this is useful to us or not but something to consider.

**Comment by Megachile** [comment]
It is if nothing else a source we can cite for defining these terms in our own glossary.

**Comment by jeffdc** [comment]
I can easily import those if we want them. I would vote yes.

Here are the decisions that I see that need to be made:

- do we even want links or maybe just a popup with the definition?
e.g.,
 
![Screen Shot 2021-04-23 at 12 50 35 PM](https://user-images.githubusercontent.com/39919/115904226-89135e00-a432-11eb-88b5-e0ddb1af67bc.png)

- do we care about auto detection of glossary terms?
    - If we do, then do we care about linking to word variations via the stem? i.e., gall, galls, galling, galler, ...
    - If we do not, I can easily enable manual linking via markdown. e.g., to link the term gall you would put emphasis markers on it, `[gall]` then this would get linked and highlighted


Linking to species is also possible in the same ways that we can link to terms. If we provide this, then we need to think about how we approach this If the links are pre-computed, either manually at edit time or when saved, they can drift as the data changes (i.e., a species is deleted, but will still be linked). If we decide this is not acceptable, then we would have to link at rendering time which is expensive, in that we will have to load the list of all species and parse the text for each page load where we want this feature.

**Comment by jeffdc** [comment]
At this point, I am pretty convinced that we want to put Markdown in place for the description field.

**Comment by Megachile** [comment]
Agreed, let's do Markdown. 

I like the tooltip idea, though if so we should strive to keep those entries short. 

I think the auto-detected links need to update regularly because many terms at least as of now haven't been added. Maybe if we made a concerted effort to complete the glossary we could do without that. Is there an intermediate solution here, where it scans every entry once a month or something? Is the resource usage an issue for our costs or just a time thing? I haven't noticed the gall pages loading slowly at all.

I would vote auto-detect for the glossary entries and manually linking for the galls. Gall links are something that it would be nice to be able to do when it seems appropriate, and having to do it manually will allow flexibility in how we format names, save a lot of headaches on your end to just have a person make those judgment calls. I doubt the links will drift often enough to be an issue but the names will still be there either way so it's not like the information will be lost, just the convenience.

**Comment by jeffdc** [comment]
The resource issue is when the pages get rebuilt (cache expires). It has to parse the text, stem the words, then link the terms. It could become an issue but it is not an issue right now.

**Comment by jeffdc** [comment]
Here is what this will look like:

- [ ] On the Host and Gall admin pages the Description field will be a simple editor like it is now (no toolbar yet). There will be a new tab control with 2 options Edit/Preview. Preview will show a rendered version of the markdown
- [ ] Basic markdown will be supported
- [ ] embedded HTML will be supported as well, this is only acceptable because only an admin can edit these fields. Care should be taken to not embed any scripts etc, just plain formatting HTML (I imagine most people will never do this but it needs to be possible to support the next item)
- [ ] Glossary terms will be auto-linked like they are now
- [ ] Glossary terms display will be enhanced to show a special visual indication that they are glossary terms (see screenshot above)
- [ ] Glossary terms display will be enhanced to provide the definition on hover
- [ ] The Host and Gall display pages will render the descriptions with formatted Markdown

**Comment by Megachile** [comment]
Sounds good to me
