### ISSUE TITLE
Create filterable gall table/add features to ID filter

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#159]
At the moment, we can filter within galls on a host genus or species using the ID tool, and show all galls induced by species in a family or genus using the Explore tool, but we can't do both at once. The ID tool also doesn't display any other info about a gall. 

I'm raising a bunch of issues together here together because I think there's two non-exclusive ways we could go about addressing them (add them to the existing ID page, or create a new page to display the data in a table (as mentioned in #148)) and it's worth discussing them in a big-picture way first. We can break them into distinct issues once we decide how to move forward. 

Possible desired features:

- Allow searching without specifying a host (eg if a gall is found on the ground, or you just want to see all galls with a certain combination of traits for academic interest)
- Allow filtering by gall inducer taxonomy (ie show only Amphibolips galls, or eriophyid galls, etc, matching other selected filter terms)
- Create a non-image table display mode that shows the DQI for a gall (#116) but also eg the family of the gall inducer and filter traits (present/absent or actual values). [Cf the one on bladmineerders](https://bladmineerders.nl/host-plants/plantae/spermatopsida/angiosperma/eudicots/superrosids/rosids/fabids/fagales/fagaceae/quercus/genus-quercus/) 
- Filter traits can be applied inclusively OR exclusively (ie, include only galls that are red and exclude any that occur in the fall but retain those without season or with other values) (no idea if this is a reasonable thing to implement or how to apply it in terms of UI but it would address the ambiguity @madeleineclaire brought up the other day and empower users to filter more specifically)

**Comment by Megachile** [comment]
> Allow filtering by gall inducer taxonomy (ie show only Amphibolips galls, or eriophyid galls, etc, matching other selected filter terms)

Someone in the Survey responses has asked for this feature as well.

**Comment by jeffdc** [comment]
The survey responder is asking for something simpler in that adding gallformer genus to the filter on the ID page would satisfy their request. That could be added independent of the larger redesign that is discussed as the main topic of this issue.
