### ISSUE TITLE
Clean up filter terms

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#160]
Textures, cells, and shape each have a mess of filter terms. We need to decide which terms should go in each and make sure we can agree on their definitions.

**Comment by madeleineclaire** [comment]
After gaining some experience entering galls, I'm wondering if we shouldn't revisit having texture and shape as filter items to begin with. They seem so subjective. 

With the idea that we could take a templated approach in general to certain descriptive features, could we simply make those fields typable and use our discretion? What I'm imagining is something similar to that image Jeff posted in the deployments section on Slack where it pulled in the colors and locations.

**Comment by Megachile** [comment]
The tension I keep coming back to on this is that a tag/filter term is just not very useful if it's not comprehensive. Like we can warn users that they're not comprehensive, but for me that always means I should just not use it and look through the full host list instead, just in case the one I need to find is not tagged. Allowing custom tags would make that problem worse.

**Comment by madeleineclaire** [comment]
In my vision, it wouldn't be a tag at all. Just descriptive text next to the image.

**Comment by Megachile** [comment]
I see. In that case I'm not sure we'd need to handle this separately from the actual description? Maybe we could have an automatically generated one for most species with an option to rewrite it manually? Or replace with the ID notes manually?

**Comment by jeffdc** [comment]
One thing that we do not have but that might help is a better global search capability. If we had a search that allowed a more complex grammar than just a search string then it would be possible to provide a better way of finding galls. A search query like:

red petiole gall on white oak

could be possible.

I think that it is good that we force structure on the admin side.

**Comment by Megachile** [comment]
I wrote up a [proposed revision of the filter terms](https://docs.google.com/document/d/161friz6WsHPah9XS5nWVc52USeQ_sBujQDBJfxvs8p4/edit?usp=sharing). I tried to define each of them in a way that would be as unambiguous as possible. I proposed a fully new filter category but otherwise tried to limit the proliferation of specific terms where the same thing could be expressed by a combination of two existing terms (eg the common erineum cup would be "leaf blister+erineum"). It is of course still very far from being able to adequately capture the range of structures, and lots of other textures and shapes especially probably still merit inclusion.

I guess just have at it in terms of adding, questioning, contesting, etc. I think by now we've each developed a sense of of our own subjective definitions of these forms and at least some of these terms and hopefully that means we can triangulate some common, consistent usage on them.

**Comment by madeleineclaire** [comment]
This looks great, Adam. I'm struggling a little bit on form. I just spent some time going through a handful of galls to see what I would assign to them and for the most part I can line up the other fields using the descriptions. What form would I use for Andricus tubifaciens? Also, can we add club or clubbed to shape?

**Comment by Megachile** [comment]
Under my proposal, A tubifaciens would either not be tagged at all or tagged as "gall," depending on whether we decided to handle that as a default case or an actively applied tag. 

My thought was that if you want to propose additional terms you need to write a definition and then see if others agree that your definition is reasonable. But yeah I think club is probably reasonable; it gets used fairly often in the literature.

**Comment by Megachile** [comment]
If no one has any more comments on this at the moment, should we go ahead and implement it and see what issues come up then? I'm sure that it's better than what we have now, no matter how we might improve it in the future.

**Comment by madeleineclaire** [comment]
I vote we proceed with the proposed changes and agree additional terms can be discussed and added as they come up.

**Comment by Megachile** [comment]
One other (minor?) advantage of using the Form category as distinct from Shape is that the generated comments would be more specific. So eg for a scale that doesn't have a picture it would say "A detachable scale" rather than gall, or "an integral leaf curl" etc

**Comment by Megachile** [comment]
It would also permit us to add a button, if we decide such a thing would be valuable in the future, that removed all gall-adjacent-but-not-gall structures from the ID filter results.

**Comment by jeffdc** [comment]
This is a decently large amount of work that will require migrating all of the current data to the new fields as well as work across the UI (ID, details display). As for the migration, every gall that uses one of the old fields will have to be migrated. If we can come up with a mapping old->new this can be automated. If the decisions are case-by-case, then someone will have to manually migrate them all. Manual migration is tricky because we have to make sure that no one is editing information for the duration of the manual migration, otherwise data will be lost or made incorrect. There are things that we can do to shorten the window but that will require extra work on my end.

In general, what it sounds like you are really after is an admin controlled and curated tagging system. 

Overall this is a major change to the system and I think that we need to plan it out at a level of detail that we mostly have not done so far. This brings up the prioritization of this vs other things. I will raise that separately for discussion.

**Comment by Megachile** [comment]
I was hoping this wouldn't require that much on your end. Eg I'm not sure I understand what part of this would require "migration"? To be clear: here's what I'm proposing:

1. Add new field (Form)

- [ ]  add to Edit Gall admin UI 
- [ ] add to ID filter selection UI. 

I had the impression that when you added Seasons this was not a major change, but if that's not the case maybe that should be a distinct feature request? No data currently exists that could map to this field so no migration of data here. 

2. Add a few terms to existing fields 

3. Remove a few terms from existing fields (afaik terms that have not been applied, though if this is not the case and people have been using them, then we might need to reconsider removing them)

4. Renaming a few existing terms (eg "2-10" becomes "polythalamous")

There's only one case (scattered and cluster move from Cells to Shape) where data would theoretically move from one field to another but afaik neither of those terms have been applied to any galls so no migration there either (ie no data would be lost if we simply deleted those and made new ones rather than mapping existing data manually or automatically). I was basically planning on going over all of the existing galls after the change no matter what, since many of these terms would have no existing counterpart.

Is that basically what you had understood or does that change your impression of how difficult this would be at all?

**Comment by jeffdc** [comment]
If there is little data to migrate then this should not be a big deal. I was under the mistaken impression that we would have to migrate a lot of field data. Renaming is easy. The tricky part is if we need to remap things to new things and delete old things.

**Comment by jeffdc** [comment]
@Megachile we need to decide what to do with all of the following data. N.B., Any and all of these may change between now and when any migration is actually run on the database. Once we figure out what we want done with these I will understand the complexity of the migration.

- Gall IDs 913 and 970 have shape `compact`
- Gall IDs 273, 461, 964, 975 have shape `linear`
- 203, 374, 918, 933, 945, 948, 951, 956, 964, 978, 989, 1118, 1130 have texture `waxy`
- 636, 759, 795, 896, 901, 905, 910, 980, 1054, 1064, 1070, 1072, 1083, 1087, 1093, 1101, 1126, 1149 have texture `stiff`
- 904, 906, 908, 994, 995, 996, 1069	have texture `felt`
- 284, 211, 47, 264, 245, 54, 261, 252 have cells `cluster`
- currently no gall has cells `scattered`
- currently no gall has walls `broken`
- 869 has alignment `drooping`

**Comment by jeffdc** [comment]
Also I have converted the spreadsheet to a migration script so any edits you make to that from hence forth will NOT be included. If you want anymore changes please list them here on this issue as a comment.

**Comment by jeffdc** [comment]
The requirement that:
 - Pubescent (always checked in conjunction with “hairy”): the hair covering the gall is short, soft, and dense. May or may not obscure the color and texture of the surface, but not concealing its shape
- Woolly (always checked in conjunction with “hairy”): the hair covering the gall is long, soft, and thick, often concealing the surface and structure of the gall completely

Is all new functionality and is non-trivial to deal with and is IMO a mistake to add. I would instead recommend that we have either 2 or 3 options that are discrete and not co-dependent. This may require re-wording or whatever.

**Comment by Megachile** [comment]
> The requirement that:
> 
>     * Pubescent (always checked in conjunction with “hairy”):

I sorry I meant for that to be like, a best-practice on the part of the admin, not a part of the code

**Comment by Megachile** [comment]
But I am definitely open to the idea of generally rethinking the vocabulary for hairs, nightmare that it is to contemplate doing so.

**Comment by Megachile** [comment]
I guess if we're using them that much already, some of those terms might as well stick around. I added definitions for stiff, linear, and drooping. But I think the rest still ought to go unless someone really wants to stand up for them. I'm struggling to define compact, waxy, and felt in ways that could be consistently applied (or in the latter case are consistently distinct from pubescent). 

Since we have a list of the galls with felt and cells: cluster, I can go in and add "pubescent" and "form: cluster" manually after the deployment. I assume that deleting doesn't require any manual work, they'll just be gone after the terms are removed?

**Comment by jeffdc** [comment]
What we should do is decide how we handle each term that we are going to delete. The options are:

- delete, this will simply remove the term from any gall that it is associated with
- remap, this requires that we decide up front what we want to map the deleted term to
- leave alone

What we can not do is rely on me generating a list from the database since that list will be out of date as soon as I generate it. The only way that will work is if we halt all editing, I generate the list, we decide on changes, apply changes, deploy, and then re-enable editing. I strongly discourage this approach and recommend the above instead.

**Comment by jeffdc** [comment]
Here is what I have come up with, any of this can be easily changed:

- delete shape:compact no other action
- remap texture:felt to texture:pubescent, delete texture:felt
- delete texture:waxy no other action
- remap cells:cluster to shape:cluster, delete cells:cluster
- delete cells:scattered no other action (maybe should be mapped to shape:numerous?)
- delete walls:broken no other action

This is just the deletions. All the other changes, additions, renames, new descriptions, will be as in the sheet.

The full migration script can be seen here: https://github.com/jeffdc/gallformers/pull/201/files#diff-55c58b31ae4fcbb5330ea6a95aa2f31f0bb4d3193c97d19f58311d9d07ea5911

Please do not make any more edits to the Google Sheet. Any problems can be addressed here on GitHub via the code review mechanisms.

**Comment by jeffdc** [comment]
These are the species that have texture:waxy: 
783
978
1647
1663
1675
1679
1682
1687
1696
1716
1727
1958
1979

shape:compact:
1640
1701

**Comment by Megachile** [comment]
> Here is what I have come up with

This is what I had in mind, I feel like we had a miscommunication somehow and I got the impression this was exactly what you *didn't* want to do. 


>     * delete cells:scattered no other action (maybe should be mapped to shape:numerous?)

Yes, though afaik it won't make a difference if there are none with that value?

The only thing this won't work for I think is waxy, since some but not all of the current values in the db are using waxy to mean "glaucous" (yet another reason it should be removed). This is something I can just click through this list and change manually though. Otherwise I think this is good to go.

**Comment by jeffdc** [comment]
Yeah sounds like we had/have a miscommunication. I need to map cells:scattered, because I have no way of knowing that it will not have been used by the time the migration is run. RE waxy if any one adds waxy to the data between when you manually went through and when I run the migration (not sure when that will happen) they will be deleted. The larger point that I am trying to make clear is that manual intervention is unreliable unless we stop all other editing of the data.

**Comment by Megachile** [comment]
I understand now, sorry. So are we good to go with this? Anyone have any last-minute objections to the changes?

**Comment by jeffdc** [comment]
I am good to go. I will post another message before I run the migration and do the deployment. I still need to work on the UI side.
