### ISSUE TITLE
Style guide/template for source sections

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#164]
I don't think it's important that every single source entry is perfectly consistently formatted, but it would be good to set some guidelines to make sure people are getting as much as possible from each source and removing superfluous/ambiguous text.

Here's what I've been mostly doing with the Weld Eastern NA entries and other random stuff, as a place to start discussion. Please challenge these guidelines wherever you feel they're misguided, propose alternatives, point out places of ambiguity, etc. 

Style:

- No quotation marks--quotation is implied
- Quote exactly and completely where the source is Creative Commons or public domain. If source is in copyright extract all factual information (hosts, range, phenology, names, etc) and quote brief description passages. Don't quote or paraphrase extensively
- Brackets to insert any clarifications/corrections I've made. Try to use these to contextualize any info that might be unclear to someone who hasn't seen the book you're quoting that is worth keeping
- Remove author of species and citations to original descriptions (I've been inconsistent about this one though, and removing this info might be a bad idea)
- Remove all anatomical info about the insect, info on type specimens, irrelevant stories about how a species was discovered or by who, info on parasitoids/inquilines, and any extraneous/unclear text (eg Weld numbers all of his species, and lists magnification values for his pictures, but these numbers aren't clear to our readers out of context)
- Remove any info relating to the alternate generation if a separate entry exists to present that info
- Adjust where it seems reasonable to avoid duplicating info or to suit the formatting in the source. Eg I often didn't make a separate section for range because Weld includes it alongside the phenology. 

Entry:

1. Species name used in the source and agamic/sexgen if applicable
2. Changes to taxonomic status if any (eg sp. nov, comb. rev., or comb. nov.) 
3. Synonyms listed in that source, if any (ie, names listed *as synonyms* by that source, not species later named synonyms listed as distinct species, see below)
4. Hosts (with updated names in brackets where necessary)
5. Index titles (eg section titles for a location or gall type)
6. Descriptions of the gall morphology
7. Info about gallformer biology relevant to ID, including phenological info about rearing.
8. Range
9. Photo captions, with number (took out the numbers for many, wish I hadn't)

If more than one species in a source belongs to a current gall, put the second species with all info above below the first entry. So eg, for Weld on [Neuroterus quercusirregularis](https://www.gallformers.org/gall/765): 

Neuroterus majalis

Quercus alba
Leaf galls, integral
Fleshy, green parenchyma thickening projecting on both sides of leaf in very early spring, 9-11 mm thick.

Quercus muehlenbergii, prinus [montana]
Leaf galls, integral
Fleshy green parenchyma thickening projecting on both sides of leaf when it is hardly half-grown.

[Photo caption]
Fig. 260. On Q alba. Also on Q prinus [montana]. Adults of both sexes out by May 6-11 (DC); June 12 (IL).

Neuroterus irregularis

Quercus chapmani
Leaf galls, integral
Abrupt fleshy thickening of large areas of leaf parenchyma, many-celled, in early spring. Like Fig 260 on Q alba [Neuroterus majalis].

Quercus stellata
Leaf galls, integral
Succulent thickened areas of leaf projecting on both sides in early spring. 9-11 mm thick.

[Photo caption (no photo)]
Gall similar to [Neuroterus majalis]; on Quercus stellata, chapmani. Galls mature before the leaves are full-grown. Adults out May 16-20, 1923; May 24-26, 1924 (DC). A heavy infestation practically defoliates the tree so that it puts forth a new set of leaves. Females were observed ovipositing on the under surface of the leaves and in September the leaves bore numbers of small galls like Neuroterus saltatorius australis Kinsey.

**Comment by madeleineclaire** [comment]
I'm good with the entry method. Directly quoting the relevant information for these specific data points and excluding everything else. Wasn't sure how much you could exclude before it became paraphrasing rather than quoting. 

Regarding style, specifically "Remove any info relating to the alternate generation if a separate entry exists to present that info," I agree that excluding any descriptive information about the alternate generation makes sense, but this makes me think we should be calling out that another generation exists and perhaps linking to it somehow. Maybe an optional 'alternate generation' field on the Add Gall screen? Wouldn't be something you'd filter by, but perhaps we could link the alt there and make it clickable?

**Comment by Megachile** [comment]
I have wished there was a convenient way to get from the gall page of one generation to the other. Maybe there's an easy way to automate that and maybe put it at the top somewhere but for the moment probably just linking to the other page in a source entry is fine.

**Comment by jeffdc** [comment]
Now that we have markdown support in the text I think that we should incorporate that into the template. Also, if we want a standard template I could add a button to generate one to save some work.

As for the gall generations, with the standard naming convention that we now have I could add a feature to the main gall page that would show any alternate generations and/or ssp. If that sounds useful create an issue.

**Comment by Megachile** [comment]
I'm not sure what you mean by a standard template? Can you show us an example of what you have in mind? How could it prefill with known info?

**Comment by jeffdc** [comment]
What I mean is that it would be nice of the system could start an empty description off with at least the outline of a template to then fill in. Github does something like this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
