### ISSUE TITLE
Rethink the location of Further Info table

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#165]
One source of potential confusion with our current Gall page layout is that, if source entries are moderately long, the currently selected source isn't shown unless you scroll down to see it. I think this makes the lack of quotation marks more problematic and it can also just be kind of inconvenient to change from one source to another. Is there a better way to arrange this? Eg what if there was a bar below the gall that listed the currently selected source, and had arrows to either side to navigate to other sources? Something like that. And maybe the copyright info tooltip should go above rather than below the source entry?

**Comment by jeffdc** [comment]
@megachile: For now I am not going to re-work the Further Info table. I do not think that what you propose is a good solution as it would require a new control that we do not have currently and it removes the ability to see all of the sources at once. One counter-proposal would be to use a list box, but I do not love that idea either. I definitely need to think about this more.

For now I am going to make it clear that the text comes from the source. I am adding quotes and showing the selected source at the top along with the  copyright info hover.

 Here is a screenshot:
![Screen Shot 2021-04-28 at 2 00 56 PM](https://user-images.githubusercontent.com/39919/116451210-366ae500-a82a-11eb-8f4d-6f6d89c8b645.png)

**Comment by Megachile** [comment]
> it removes the ability to see all of the sources at once

I was thinking this would be in addition to what we have now, not replacing it. But I don't think it's that important either way, just a thought. 

I think your changed format for the title, copyright indicator, and quotation marks are great and address the more important point very well.

**Comment by Megachile** [comment]
we can close it.
