### ISSUE TITLE
Should we build a gall comparison tool to help ID similar galls? 

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#166]
Our goals seem to be sort of in two tiers: to present high-quality, accessible info on IDing the most commonly encountered gall species, and providing filterable lists and sources for the others thousands of species with minimal info available (helping, in the long term, to move those into the first category). Based on discussion in #94, for many users, quotes from primary sources may not be sufficiently accessible. Adding our own descriptions might help, but ultimately they're just more big blocks of text. 

One key use case for that kind of user is distinguishing possible candidates, and while text can achieve that, illustrations are much more effective and accessible. I think the [comparison tools on bplant.org](https://bplant.org/compare/787-2768) are a great model for what that might look like. 

I feel like this would be quite a bit of work to build relative to the kinds of things we have already, so I don't know if it would be worth it. Thoughts?

**Comment by jeffdc** [comment]
That tool is pretty great and I agree that something like this would be super helpful. It is a good bit of work, but to me worth it.
