### ISSUE TITLE
Add Taxonomy Management Screen

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#167]
This is maybe a fairly unusual situation, but it could conceivably come up again I guess. I made a gall "Eriophyes dentatae," which is slotted into family Eriophyidae because of its genus. But the gall turns out to be an undescribed cynipid wasp, so I changed the name to Unknown dentatae so it'd move into the right family. Because "Unknown" was first (or maybe still only?) applied to cynipids, it put it in the right family, so there's nothing that needs to be changed here. But if that were not the case (if this were a midge or something) it would not be possible to correct the family because the db thinks "Unknown" is always a genus of Cynipidae. I thought it was possible to overwrite that on the gall page but it doesn't seem to be.

**Comment by jeffdc** [comment]
New unknown genera get created when you create a new Undescribed species and assign it to a family that does not already have an 'Unknown' genus. 

The core of the problem here is that the site is trying to use rename to manage taxonomy which is probably a mistake. The solution, I think, is to allow renaming a species but not allow editing of the genus at that point and then to add a new screen to manage the taxonomy of a species.

**Comment by Megachile** [comment]
That makes sense to me.

**Comment by jeffdc** [comment]
# Summary of Issue
Currently there is no unified way to see and edit the taxonomy for a species. While it is possible to edit the taxonomy it is all done via renaming and opaque under the hood hoop jumping by the code. The original issue that came up, "Not possible to alter family of undescribed species after gall is made", is likely just one problematic scenario that currently exists.

## Proposal - Replace the Rename Modal with a Taxonomy Edit Screen
This screen will allow an admin to edit the Family and Genus for a given species (host or gall) as well as to rename the species. 

- [ ] The screen will be a modal accessible from the current Edit Host/Gall admin pages
- [ ] It will have 3 fields, the current Family, Genus, and Specific Name for the species
- [ ] All fields are editable
- [ ] The Family and Genus fields will use the standard typeahead control that is used throughout the site
- [ ] If the Family is changed, the Genus will be cleared and a new Genus must be selected
- [ ] If the Genus is not present, then a new one can be added via this screen (again using the standard typeahead control)
- [ ] If the Family is not present, then the admin will have to first go to the existing Family edit screen and add it

### Changes to Existing Functionality
- [ ] The new modal will necessitate making the Genus & Family fields on the main Host/Gall edit pages read-only
- [ ] Change the "Rename" button to "Edit Taxonomy"

**Comment by Megachile** [comment]
This sounds good to me. Is there anything to do with changes we might make for #169 we should plan for in the implementation of this or is it fairly independent of whatever we might do for that?

**Comment by jeffdc** [comment]
As part of this it will be possible to delete the Genus under a Family. When that happens we will delete ALL of the species that are assigned that Genus. I have added a warning to make this clear, but this is an area where much havoc could be wreaked by accident. Here is what the warning looks like
![Screen Shot 2021-11-24 at 11 40 03 AM](https://user-images.githubusercontent.com/39919/143279203-9f827591-969e-4d00-b29a-c91b20a915cd.png)

This pops up when the user hits the Delete button on the Genera table. I tried to make it clear that the actual deletion does not happen until the Submit button on the main page is pressed (where there will NOT be another warning).

The other thing that this brings up is that we do not have a Cancel button on the Admin pages. You can effectively Cancel by refreshing the page but it is not the most obvious UX. Adding Cancel across the Admin pages is a decent amount of work but could be done if it is a priority.

Thoughts?
@Megachile
