### ISSUE TITLE
Rethink mapping at the genus level 

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#169]
We've had #50 in place for a while now and with some experience, I think it's a very inadequate solution to the problem it was meant to address, in several ways. For one thing, it's not actually possible to use the bulk section-level association because whenever that would apply, it should only be within a certain region. IE a gall found on "all red oaks" in eastern US shouldn't be associated with lobatae endemic to CA. Another issue is that the tool only applies to species in the genus that have already been added to the database, so hosts added later that should be mapped are not. 

The thing that really bugs me, though, is that it implies an unwarranted level of certainty. Eg I mapped Taphrina caerulescens to Quercus today, and the page lists every Quercus species in the US. That might be close to true for T caerulescens actually, but in most cases it's more like "this gall is on 1 or maybe 5 out of dozens of species in this genus, we just don't know which they are." So listing them specifically conveys exactly the wrong message. 

What we want is to list them on the filter results as possibilities, because we don't know which host species they should show up on (hence the logic of #50 being the way it is now), while communicating our limited knowledge on the gall page. I don't know what the best solution would be, but here's some ideas to start with.

There are kind of two distinct cases here. One is that a species was described from one unknown host in a genus. 

In this case, what if we created an mechanism to list "[Genus] sp." as a host somehow? That would show our knowledge correctly on the gall page and the gall would appear in the genus ID filter results. Then, potentially, we could also make any species tagged this way appear in the results for any species in that genus, (potentially under some kind of marked partition to communicate the gap in knowledge?).

The other is that it's known from many in a genus but the exact bounds are not known (or simply don't appear in any sources available). 

In that case, instead of using genus-level mapping as a a bulk species mapping tool, mapping at the genus level should be a distinct operation. In that case, too, species marked this way would be listed in the ID filter results when the genus was selected and when any species in that genus was selected. On the gall page, the host field would read "Hosts: [Genus] spp." This option could be selected in addition to as many specific species that were known as possible, to communicate which ones were confirmed, within that larger relationship.

These solutions wouldn't solve the region issue and would create a lot of false positives in species-level searches, which is not ideal. But they would be future-proof.

As always, not sure this is the best or worthwhile way to solve this problem, just raising the issue and putting some ideas out there.

**Comment by jeffdc** [comment]
I am ready to look at this as well as #167 and #222. It is has been a while since these were written up. @megachile, is your thinking still the same for these? Are there any other related issues that you can think of?

We definitely need something like #167. I am wondering if we need a more comprehensive taxonomy management screen? The use cases I can think of are:

- Add/Edit Family name and "common name"
- Add/Edit Genus name and "common name", would cover #222 
- Move Genus to different family
- Delete Family or Genus

This would eliminate the need for the current Family admin screen.

This would fully promote Genus to a first class citizen in the data model like Family already is. I will need to do some work to make sure that the species name couplet is kept in sync with any changes to genera names.

N.B., the common names on Family and Genus are not aliases like we have at the species level. There can only be one common name per Family/Genus. If this is insufficient I would need to do some work to implement full blown Aliases for Family and Genus.

It is possible we would want to put some of this functionality behind the "super admin" permission.

**Comment by Megachile** [comment]
I think the proposals I made above are still basically what I want to happen (open to other input of course), but I wonder if now that we've added range functionality, maybe there's a way to mitigate some of the range-related issues I pointed out? This may not be feasible--unless I'm missing some elegant solution here, it would involve creating a new relation in the database, which may not be worthwhile. Eg we could create an optional gall-side range field that overrides the ones inherited from linked hosts (which may also come in handy if we find there are galls with ranges we can confidently say are much narrower than those of their host). That would let us say eg a gall is found on all Lobatae in XYZ states, or if a gall was known from one type location but the host was only known to genus, we could narrow it to that one state. Idk, let me know if you can think of a better way to handle that given the data we already have, or if it's just not worth it. 

Does "Move Genus to different family" cover my original case in #167 (or the one I asked you to fix the other day?). I didn't want to move the whole genus, just remap the genus from one to another. 

I think it's fine to have one common name per genus; that should be plenty for most cases. 

I'm not sure I see a need to add common names at the family level since they don't appear in the ID tool, though I have no objection to adding them.

**Comment by Megachile** [comment]
Do you want to think about #234 at the same time here?

**Comment by jeffdc** [comment]
RE moving genera, Move genus does not cover the case you brought up. That will happen on the Gall/Host screens. Here is my thinking for that:

**Gall/Hosts Changes**
- Change the 'Rename' Button to indicate that it is also used to move the species in the taxonomy
- On the Rename/Move UI:
    - Split into 3 fields:
        - Family - typeahead box with all families
        - Genus - typeahead box with all genera for selected Family
        - Specific - freeform text - will also address #235 as part of this
    - Same Save/Cancel buttons and Add Alias checkbox
    
RE Mapping Genera:

Here is my proposal:

- Add a new table to allow gall-genus mappings
- Add a confidence to both gall-host and gall-genus mappings (i just made these up we need to think about what these should actually be)
    - Confirmed
    - Likely
    - Theoretical
- default all mappings to "Confirmed"
- change the ID screen to have a filter for this confidence
- change the ID screen to visually indicate the confidence when displaying results
- change the Gall details screen, replace the current host display with a table
    - sortable, paged
    - shows Host species/Genus and confidence
- add confidence to the Host details Gall table

As for handling ranges, that is more tricky. I think that if we want to start mapping ranges to galls directly we need to step back and rethink the entire way we map galls to hosts. This would likely end up with large changes to the database and require a good deal of work across the board. It is certainly doable (I would need to put more thought into exactly what these changes would be). How important in the short term and the long term do you think being able to map a gall directly to a range is?
