### ISSUE TITLE
Site links in markdown broken by glossary link

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#172]
In the map source tool, I can make a link to a gall page and the preview works. But when I submit and check on the gall page, it's broken, and I suspect it's because of the link to the word "gall" in the URL of gallformers. See the Weld 1926 entry here: https://www.gallformers.org/gall/783

**Comment by jeffdc** [comment]
Ahh the joys of parsing and formatting text...

**Comment by Megachile** [comment]
I feel like it'd be fine to just turn off the glossary for the time being?

**Comment by jeffdc** [comment]
I am going to turn it off per your suggestion and am working on a much better solution.
