### ISSUE TITLE
ID Filter results displays raw text including code

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#175]
Not sure this is a problem we can/need to solve but it's a bit ugly, at least, that the ID filter results just shows raw code. So eg [it looks like this](https://www.gallformers.org/id?hostOrTaxon=Quercus+montana&type=host&detachable=detachable&alignment=&cells=&color=&locations=leaf+midrib&season=Fall&shape=&textures=&walls=) if the default source contains a lot of links.

**Comment by jeffdc** [comment]
I can fix it pretty easily.

**Comment by jeffdc** [comment]
I think that the larger question is what should we be displaying here? Currently it simple displays the default description truncated after 40 words which may or may not be useful.

**Comment by jeffdc** [comment]
For now I am changing it so that it will display the entirety of the default description with the markdown formatted properly (no glossary entries).

**Comment by Megachile** [comment]
I think what we have now is the best we can easily do. This is basically an extension of the issue discussed in #94--we'd like to have everyone browsing the ID results to see a short description, so ideally we'll either select a source that best achieves that or write one ourselves. There will be cases where that isn't possible but we'll do the best we can. 

Displaying all of the default source might be too much--they can be pretty long. Maybe a happy medium, longer than 40 words but not totally unbounded?

**Comment by jeffdc** [comment]
I am going to try it with the full description for now. I agree that we need to come up with something better, a-la #94
