### ISSUE TITLE
Glossary links in Source entries on gall pages go to 404

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#176]
The hover text shows the definition of each term but if you actually click on any of the highlighted words they take you to a 404 page.

**Comment by jeffdc** [comment]
I have this one fixed already. Will get deployed as soon as I get the other ones taken care of. I have a little bit of time tomorrow but realistically will not get all these done until tomorrow or Tuesday.

**Comment by Megachile** [comment]
Sounds great, no hurry
