### ISSUE TITLE
Explore page doesn't allow middle-clicking to open in new tab

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#178]
Extremely minor issue but: right now it's apparently not possible to browse a genus in the Explore page and open a bunch of hosts or galls in new tabs using the middle click (scroll wheel) button. You have to click on one, replacing the explore page with the one you selected. This button works on other parts of the site--is it possible to make that functionality work here as well?

**Comment by Megachile** [comment]
The same applies to the individual family pages (though not genus).

**Comment by jeffdc** [comment]
This is a limitation of the tree control that we are using to display these browse pages. I was hoping for a quick fix but it was not forthcoming. I will come back to this as it is really annoying!

**Comment by jeffdc** [comment]
Did not mean to close this one.

**Comment by Megachile** [comment]
This function works on the "edit gall" and "source" edit pencils on a gall page but not the "image" pencil.

**Comment by jeffdc** [comment]
I made it so that the edit image link works this way. At least on my Mac. I can not test it on Windows. The problem here is that the browser handles middle/ctrl/command/meta clicking on links but these are not actually links but buttons or other UI elements. I tried to implement code that mirrors the way the browser behaves but am not sure that it works with all OS and browser combinations. 

The problem in the Explore trees still exists however as I do not have access there (3rd party) component to the click event to be able to parse out the type of click. I think that they only way to fix that one is to entirely replace the component or to modify the component, open a PR against that repo and hope that the maintainers take it. Both are a good deal of work.

**Comment by jeffdc** [comment]
@Megachile other than the middle click problem, are there any other issues/annoyances/wishes for the explore pages? To enable middle-click/cmd/ctrl-click open in new tab I will have to replace the tree control that is being used. At this point I think that this is only worth the effort if we want to rethink the explore pages and how they work. They are something I just added on a whim and do not have a lot of features as of yet. Maybe we can think more about them and come up with something more useful.

**Comment by Megachile** [comment]
Personally it's not something I currently use much or find myself wishing I could use differently. For its function, I'd rather have something like the table discussed in #159, with the ability to filter by host and/or taxonomy but also see other information. Something that would let me check eg whether all the Amphibolips galls have "walls" tags or all the Quercus alba stem galls have a season tag or whatever.

**Comment by Megachile** [comment]
Just got this message from an iNat user: 

"First, I wanted to let you know that I really appreciate the Gallformer website and I think it is quite an useful resource!

However, one feature of this website that I have some issues with is the Explore feature : personally, I like to casually browser species by families, and see the diversity of galls. Unfortunately, each time you click on genus on the explore page, there is no way to go back without resetting the Explore feature, which make looking at various species from the same family very tedious

on many websites when you right-click on a name, there is an option to open the link in a new tab, which is not available here (opening species in a new tab), which is a bit jarring considering that this option is available for gall species for individual host (i.e. you can open a new tab for each species of galls when you are on an host page).

Of course I have no idea if this is something that can be changed, but I think that this issue might have the merit to be considered for easier casual browsing of families in the Explore section"
