### ISSUE TITLE
Show host DQI on ID page

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#182]
At the moment, the only way to know whether the ID results for a host you select on the ID page are comprehensive is to search the host and click through to the page. I don't think many users are likely to do this, so it's probably often unclear whether the filter results they're looking at is (to our standards) "complete." How can we communicate this? Maybe an icon in the dropdown next to completed hosts? Or a thing that pops up somewhere around the filter results once a host is selected telling the user whether the DQI is checked or not?

**Comment by jeffdc** [comment]
@megachile how does this look? I added text to the blue box above the results. If you select a Section or Genus no new text is displayed.

![Screen Shot 2021-05-05 at 9 43 33 AM](https://user-images.githubusercontent.com/39919/117150716-65cba580-ad86-11eb-9654-22c44f71bc45.png)

![Screen Shot 2021-05-05 at 9 43 21 AM](https://user-images.githubusercontent.com/39919/117150718-66643c00-ad86-11eb-8ddf-1113ad69acfa.png)

**Comment by Megachile** [comment]
I couldn't figure out what you had changed until I reread your text, so I don't think it's visible enough to really work.

**Comment by Megachile** [comment]
What if we removed the current generic warning box at the top and replaced it with a contextual one depending on the host?

**Comment by jeffdc** [comment]
I think that is a good idea. I am also really not loving the giant yellow box at the top of the ID page. I understand the intent of it, but it is so intrusive.

**Comment by jeffdc** [comment]
Here is what it looks like now. If the host is complete then there simply is no yellow box.

![Screen Shot 2021-05-05 at 2 39 21 PM](https://user-images.githubusercontent.com/39919/117192440-b99eb480-adaf-11eb-8aa2-14727d82cb82.png)

**Comment by Megachile** [comment]
I like it. I do think it would be worthwhile to have the other case as well, something like "to our knowledge, every gall that occurs on the host you have selected is included in the database. If you find a gall on this host that is not listed below, contact us at gallformers@gmail.com."

**Comment by jeffdc** [comment]
It is very intrusive and takes up a lot of space if I add that. See: 
![Screen Shot 2021-05-05 at 3 14 34 PM](https://user-images.githubusercontent.com/39919/117196559-a17d6400-adb4-11eb-8898-c58fd6e11b38.png)

It also seems partially redundant with what is in the blue box. I really feel it is better to only alert the user to the case where information is incomplete. It seems weird to have an alert that the information is complete. Maybe instead we add the text that you mention above to the page that is linked in the current blue box.

**Comment by jeffdc** [comment]
How about this?
![Screen Shot 2021-05-05 at 3 23 01 PM](https://user-images.githubusercontent.com/39919/117197429-ce7e4680-adb5-11eb-9e28-1c67edc42f26.png)

**Comment by Megachile** [comment]
I think that seems reasonable
