### ISSUE TITLE
Error message upon trying to delete family

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#194]
Receiving an error upon trying to delete a family. 
![Capture](https://user-images.githubusercontent.com/16893725/119210725-bed05480-ba7b-11eb-9e10-b3630defa89f.JPG)
 The family in question contains an accidentally added plant genus, which I am trying to remove.

**Comment by jeffdc** [comment]
Note to Jeff: there are also two copies of Rudbeckia in the DB. 

In general I think we need a better way to handle maintenance of the taxonomy. This came up in previous issues. I will find them and resurface the conversation.

**Comment by jeffdc** [comment]
This one I was able to replicate and will work on a fix for it.
