### ISSUE TITLE
Error upon attempting to add new source

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#195]
![Capture](https://user-images.githubusercontent.com/16893725/119214640-63f82680-ba96-11eb-83f0-ac59dcf3baea.PNG)
Attempted to add new source to Rhabdophaga rigidae, received error. Similar (same?) to one seen earlier.

**Comment by jeffdc** [comment]
@licoriceleaf to get the errors out of the console follow these instructions. https://appuals.com/open-browser-console/  I will add a link to instructions in the error message as well so that in the future folks will know how to do that.

**Comment by jeffdc** [comment]
In the screenshot you seem to be on the Create Source page but the selected tab is the "Galls" tab which is quite perplexing to me. If you can try and recreate this problem and grab whatever is int he console and paste it here that would be helpful. I was not able to replicate any kind of error when creating a Source. I tried to first create a Gall and then a Source which is what I assumed you were doing when this happened.

**Comment by licoriceleaf** [comment]
Alright, here's what I'm getting from the console -
![Capture](https://user-images.githubusercontent.com/16893725/119235618-6774c780-bb01-11eb-94d2-8b2ec60e30d5.PNG)
I was unable to recreate "Galls" as the selected tab this time.

**Comment by jeffdc** [comment]
Can you outline the steps that you are taking to get this error because I am not able to replicate it. Just write out each step you take, what you click, etc that produces the error.

**Comment by licoriceleaf** [comment]
Essentially, I input all the necessary information into the boxes in the Add/Edit Sources tab. I then click 'Submit', and this error is immediately returned to me.

**Comment by jeffdc** [comment]
I added the source: https://www.gallformers.org/admin/source?id=198

I think what is happening is that  when you are adding you are not selecting "Add ..." when you type in the new name. 

You have to explicit tell it you want to add a new source. See screen shot below:
![Screen Shot 2021-05-25 at 10 07 28 AM](https://user-images.githubusercontent.com/39919/119512425-4a2e3c00-bd41-11eb-8502-29afb789a247.png)

**Comment by jeffdc** [comment]
I will make it so that the Submit is inactive if the input is invalid. That will prevent this error from happening.

**Comment by licoriceleaf** [comment]
Thanks, I tried to add some new sources the other day and they submitted without any problems as well.
