### ISSUE TITLE
Image box not resizing?

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#203]
![Capture](https://user-images.githubusercontent.com/16893725/121750087-bd71d500-cad9-11eb-807c-8548acf4fe8d.JPG)
Only just experienced this issue today, but gall pages with multiple images seem to retain the size of the default image, if that makes sense. As such, the full image is not shown.

**Comment by licoriceleaf** [comment]
Another example --
![Capture](https://user-images.githubusercontent.com/16893725/121750324-29543d80-cada-11eb-8d05-b4e309f089ed.JPG)
![afa](https://user-images.githubusercontent.com/16893725/121750326-29ecd400-cada-11eb-94fd-7dc79d521873.JPG)

**Comment by licoriceleaf** [comment]
Another example --
![Capture](https://user-images.githubusercontent.com/16893725/121750387-4be65680-cada-11eb-80f3-98fa42f77b68.JPG)
![afa](https://user-images.githubusercontent.com/16893725/121750390-4c7eed00-cada-11eb-9155-9a41a9dd7f83.JPG)

**Comment by Megachile** [comment]
This is an intentional solution to prevent the page from creating too much white space, not a bug. It's a tradeoff but it's the current way we've decided to handle it.

**Comment by Megachile** [comment]
You're welcome to edit the issue to propose an alternate way to handle this problem but if not, you can close it.

**Comment by licoriceleaf** [comment]
Thanks, will close. Wasn't aware this was intentional

**Comment by jeffdc** [comment]
Here is the original issue where this was discussed: #192
