### ISSUE TITLE
Update ID Tool Filter Guide to reflect new terms

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#212]
To accompany the changes made in #160, we need to update the Texture, Alignment, Walls, and Cells sections of the ID Tool Filter Guide page, and add a Form section, in accordance with [this document](https://docs.google.com/document/d/161friz6WsHPah9XS5nWVc52USeQ_sBujQDBJfxvs8p4/edit).

**Comment by jeffdc** [comment]
This will happen automatically after I apply the database changes. I was thinking that you wanted special handling to eliminate the non-galls by default.

**Comment by jeffdc** [comment]
Never mind. I misread, this is the Guide not the ID page. Oops.
