### ISSUE TITLE
After submitting info on Edit Gall or Host, it takes two clicks to browse to different tab of Admin toolbar

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#214]
If I have no gall selected, or open an existing gall in one page (eg Galls), then click another tab like Source Map or Images, it loads that tab. But if I have a gall selected and hit submit (whether I've made any edits or not), then click a different tab, it acts as if I've reloaded the gall page rather than loading the one I selected. If I then click the tab again (because reloading has reset me to the original state without having hit "submit") it works. This doesn't happen if I middle-click to open in a new tab so I've mostly been doing that instead. 

https://user-images.githubusercontent.com/69063635/123309093-7aa8f780-d4f2-11eb-8faa-0dcda9f30de6.mp4

**Comment by jeffdc** [comment]
I can not replicate this. I also made changes to this page that may have fixed it. Once I do the next deployment we can re-check this to see if it still occurs.

**Comment by Megachile** [comment]
Still happening for me after the deployment.

**Comment by jeffdc** [comment]
This only fails in Firefox. Works in Chrome and MacOS Safari. It may be a PITA to track down. I think we should leave it open as low priority.
