### ISSUE TITLE
Cells not showing on gall page

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#219]
![cellular](https://user-images.githubusercontent.com/16893725/123491132-fe8edc80-d5e3-11eb-9560-2da8185c60ad.JPG)
The gall description page does not show the cells despite them being an enterable field on the gall edit page.

**Comment by jeffdc** [comment]
Oops. I messed it up when adding Form. I will fix it and get it deployed tomorrow.
