### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#22]
Add the ability to CRUD data. This requires authN/authZ. Use Auth0 for this.

**Comment by garrisons** [comment]
Uh oh. @jeffdc @jorgerasillo are busting a move in NextJS. Dance off?

This might help make Auth a little easier on the UI side: https://next-auth.js.org/

Also, this is what I’ve been using recently: https://blitzjs.com

Not sure if it’d be worth porting, but their Auth, session management, etc is interesting and was spec-ed by the supertoken folks.

**Comment by jorgerasillo** [comment]
@garrisons hah, it's all @jeffdc I'm just here for the 💩 and giggles :)

**Comment by jeffdc** [comment]
@garrisons 🕺  next-auth.js looks pretty compelling. I will check it out. I chose Auth0 because it was free and they had a decent React hook to integrate with. My needs are pretty simple, though it would be nice to eliminate the hosted 3rd party (commercial) dependency.

**Comment by garrisons** [comment]
@jeffdc i think next-Auth might have a provider for Auth0 if you wanted to keep using it too.

**Comment by jeffdc** [comment]
@garrisons They do indeed. I integrated it this AM: https://github.com/jeffdc/gallformers/pull/21/commits/68effcdb136d0d0c86941e9e4d2a884f68657cd2

**Comment by garrisons** [comment]
Oh nice! 🚴🏼
