### ISSUE TITLE
Error upon attempting to add to gall

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#221]
![Capture](https://user-images.githubusercontent.com/16893725/123495631-811e9880-d5f2-11eb-8574-a5e948ec295e.JPG)
Within the past hour or so I've been receiving this error that prevents me from adding anything to any of the drop-down selections in the admin edit tab.

**Comment by licoriceleaf** [comment]
Error message in console: 
![image](https://user-images.githubusercontent.com/16893725/123495750-f1c5b500-d5f2-11eb-8982-6e62de221004.png)

**Comment by jeffdc** [comment]
Fixed it. It was an issue with the underlying hardware.
