### ISSUE TITLE
Support common names at the genus level

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#222]
I've been using both common and latin names to make sure that the database will function for both as I do spot checks etc, and I realized that this is possible for species and sections but not genera. Eg if you type oak in the genus field you'll get red, white, etc oaks but not Quercus. It seems like it is probably worthwhile to add common names to genera on the same logic as species.

**Comment by jeffdc** [comment]
This is dependent on #167 as there is currently no way to edit genus names other than editing a species name. The data structure is there we just do not have UI to manage it.

**Comment by jeffdc** [comment]
@Megachile do you think that this will work?

![Screen Shot 2021-09-03 at 4 12 59 PM](https://user-images.githubusercontent.com/39919/132061051-1a911c34-d347-46b6-bbf9-a3b668a5c23a.png)

If you select one or more Genus you get:

![Screen Shot 2021-09-03 at 4 15 19 PM](https://user-images.githubusercontent.com/39919/132061168-4baaa36b-b944-44e5-9ecf-f0ac95559523.png)

I am still thinking through how the "Move" workflow will work and will post a screenshot once I get it sorted.

**Comment by Megachile** [comment]
It looks good to me.

**Comment by jeffdc** [comment]
@Megachile how does this look?
![Screen Shot 2021-11-13 at 4 44 59 PM](https://user-images.githubusercontent.com/39919/141659889-9e1d8b9d-2068-4204-b290-fcb77180045d.png)
![Screen Shot 2021-11-13 at 4 44 42 PM](https://user-images.githubusercontent.com/39919/141659892-471a58d8-0a76-43c3-ba28-44038b020c19.png)

**Comment by Megachile** [comment]
Looks like it should do the job.
