### ISSUE TITLE
Change behavior when "Detachable: Both" is selected in ID filter

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#224]
Currently, selecting "both" in the gall edit page causes a gall to appear in both integral and detachable ID filter results, as intended. However, selecting "both" on the ID filter page currently shows results that have either integral, detachable, or both, selected. This seems useless--selecting both is the same as leaving the field blank. If this is all we want it to do, there's no reason to show the "both" option to ID users at all. But I have a couple times found myself wanting to see only the entries with Both selected, and thinking this is what should happen when I select both. Can/should we change it to behave this way?

**Comment by jeffdc** [comment]
This should be an easy enough change and I agree it is kind of odd the way it works now. I will add it in with my next batch of changes.

**Comment by jeffdc** [comment]
One point of clarification in what you wrote:
> ...selecting both is the same as leaving the field blank

This is not true. If you leave the field blank you will get all galls regardless of the value of Detachable, including those with no value whereas with 'Both' you not get those that have no value. If you look at Q alba bud galls for example, there are 17 with Detachable blank and 13 with 'Both' selected.

**Comment by Megachile** [comment]
>  If you look at Q alba bud galls for example, there are 17 with Detachable blank and 13 with 'Both' selected.

True, but that's a function of incomplete data and doesn't tell anyone anything meaningful in the sense that would make it a useful filter behavior.

**Comment by jeffdc** [comment]
Agreed but I just wanted to make it clear that this currently exists and with the change it will no longer be possible.

**Comment by Megachile** [comment]
Got it, okay. I do think it would be nice to have an interface that lets you see areas of data incompleteness (though this does the opposite--not sure I can think of any use for it?) but that's a different conversation.
