### ISSUE TITLE
Error 500 upon attempting to add new host

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#225]
![Capture](https://user-images.githubusercontent.com/16893725/124405400-870c2c00-dd0c-11eb-8185-11b0985059ba.JPG)
Attempted to add a new host, Aristida longiseta to the db today yet was met with this error.

**Comment by jeffdc** [comment]
Was it this host? https://www.gallformers.org/host/2619

**Comment by jeffdc** [comment]
I am not sure what happened but I need to delete this: https://www.gallformers.org/host/2619

It has no data associated with it so it should not be a big deal. I will try and re-create it. It is somehow missing both its genus and family which is causing the host admin to not load..

**Comment by jeffdc** [comment]
I deleted and re-added and all seems ok: https://www.gallformers.org/host/2619 Not sure what happened. Something went wrong when adding that host originally. Like I said, somehow it had not Genus or Family assigned to it.

**Comment by licoriceleaf** [comment]
Alright, I originally added that host and genus because I was reading the Gagne catalog and thought that there was a species that formed galls on there. So I added the family and species, but I read more closely later and found out it was an inquiline. And so I attempted to delete the host family that was added.

**Comment by licoriceleaf** [comment]
Looks like it works now, just successfully added host

**Comment by jeffdc** [comment]
I will test (and fix) the Family deletion code that seems to be what went wrong.
