### ISSUE TITLE
Failing to add new undescribed gall

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#227]
https://user-images.githubusercontent.com/16893725/124503377-705ce800-dd93-11eb-89d8-eb167f4b6e1b.mp4

Attempting to add a new undescribed gall yet clicking on 'Done' doesn't add it.

![image](https://user-images.githubusercontent.com/16893725/124503461-9d10ff80-dd93-11eb-9c09-12b3282a5792.png)
Here's the console

**Comment by jeffdc** [comment]
A Family must be assigned to the gall species. If the genus is unknown you should check that box at the top., otherwise you have to assign it to a Family, which could be the Unknown family. I should make a better error message but that is what is happening.
