### ISSUE TITLE
Add Validation to Family on Undescribed Gall Creation Screen

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#228]
A Family must be assigned to the gall species. If the genus is unknown you should check that box at the top., otherwise you have to assign it to a Family, which could be the Unknown family. I should make a better error message but that is what is happening.

_Originally posted by @jeffdc in https://github.com/jeffdc/gallformers/issues/227#issuecomment-874258822_

**Comment by jeffdc** [comment]
I cleaned up the screen and added more help text and made it so that the Done button is disabled until all of the required fields are filled in.

![Screen Shot 2021-07-06 at 10 26 55 AM](https://user-images.githubusercontent.com/39919/124617237-c50c6b80-de44-11eb-813c-d7a8b8545195.png)

Thoughts?
@licoriceleaf
@Megachile

**Comment by Megachile** [comment]
Looks good to me.

**Comment by licoriceleaf** [comment]
Nice, looks good.
