### ISSUE TITLE
New proposed filter terms

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#231]
Texture:
Ruptured/Split - galls emerge from the host plant through a visible rupture in the tissue they form in. Typically observed in stem and occasionally midrib galls. Split edges may not be apparent if galls are large.

Mealy - galls appear to be coated in a coarse, granular texture, like flour or cornmeal. This appearance may be caused by a fine bumpiness of the solid exterior of the gall or a layer of short hairs, such that the mealiness may or may not be removable.

**Comment by ddennism** [comment]
"form: modified capitulum"

Flowers in Asteraceae are clustered into tight structures called "capitula", which themselves resemble a flower at first glance. Developing capitula have the overall appearance of flower buds, and are sometimes called "flower buds" or "inflorescence buds" in technical and popular literature.  Several gall-formers develop within developing capitula. These occupied capitula are referred to as galls, even when there is not an obvious external difference. There are usually at least some external clues (arrested development vs. nearby capitula, color change, change in texture, swelling, etc.), however.

These could be shoe-horned into "abrupt swelling", but there are cases that do not always involve swelling. Sometimes the galled capitula are smaller than the surrounding capitula
![asphondylia_pseudorosa_capitulum_gall](https://user-images.githubusercontent.com/88114774/128095813-5ffe832f-3288-47cc-80f6-144e9741bb65.JPG)

**Comment by ddennism** [comment]
"walls: mycelium lining"

Some galls, sometimes called "ambrosia" type galls, have walls with a fungal inner lining. Examples include those produced by Asteromyia and some Asphondylia species. In some cases the developing midge larva feeds on the fungus; in other cases the role of the fungus is unknown. It may be important for inducing the gall.

These fluffy or filamentous linings can be useful for identification. I think they would be useful as a field. This is distinct from occasional fungi found e.g. in decaying galls, which are not an intrinsic feature of the gall.

**Comment by ddennism** [comment]
"location: rhizome"

**Comment by Megachile** [comment]
Can you define rhizome as distinct from roots? Are there cases where root v rhizome is a diagnostically important trait for enough galls that we'll want to have it in the filter tool?

**Comment by Megachile** [comment]
Form:
Leaf snap - two distinct, otherwise typical host leaves are joined together around a gall cell

**Comment by jeffdc** [comment]
I have changes ready for all of these other than rhizome. Any decision on it?

**Comment by jeffdc** [comment]
@megachile, as part of this work I am making it so that the Filter Guide page is generated from the data in the database (since we already have all of the filter term definitions in there). This will make it so that we do not have to update these in 2 places anymore. The database will be the source of truth for these terms and their definitions. Maybe as an enhancement we would also show these as part of the glossary.

**Comment by Megachile** [comment]
@ddennism any thoughts on the rhizome thing? I'm open to it but my instinct is to think it's more likely to confuse and complicate things without adding much benefit. But that's mostly based on oak galls where there just aren't that many in the first place.

And what do you want to do for definitions? Are the ones you wrote here good to use or do you want to edit them at all?

**Comment by ddennism** [comment]
@Megachile - I see your point about the distinction between rhizomes and roots being lost on the casual site user, but it's a pretty fundamental difference. Rhizomes are stems. Unlike roots they have nodes, buds, subtending leaves (often scale-like or otherwise vestigial), and a radically different internal anatomy. To be honest, if I saw a source that conflated the two, I'd write it off as unreliable out of hand for making such a bizarre mistake.

But I understand the need to keep these filters low-in-number, accessible to everyone, and simple. What about "underground stems" (which has the benefit of including non-rhizome underground stems)? Or even just "attached underground" or "subterranean" to include roots and all other underground plant organs?

Emergent and "crown" galls pose another complication. One common situation (e.g. in *Eurosta comma*) is for a gall to develop on an underground organ (usually a rhizome) and then grow up and out of the ground when the insect emerges.

**Comment by ddennism** [comment]
"shape: cylindrical" to accommodate, for example, *Rhopalomyia anthophila* and *Rhopalomyia guttata* galls.

**Comment by Megachile** [comment]
I see why you'd want them separated to be technically correct. This is something we have to wrestle with in lots of things. Eg "fruit" currently encompasses every part of a fruit, regardless of fruit type or whether the gall is in the seed or pericarp etc. Fern leaves are still leaves even when they are fern pinnules or whatever. 

I have a couple thoughts about how to handle this. If you expect to have a large group of galls on a single host that is on the roots, and a decent number on rhizomes, then we can add them as separate structures. If not, and the issue is just the naming question, we could just rename root, as you suggest, eg either "root/rhizome" or "underground." 

Right now we have a lot of root crown galls listed as root galls because the sources lack clarity in distinguishing the two, and/or there is variation that indicates the gall occurs on either (which of course could be handled by tagging both). In theory we could go even farther and make separate tags for all of them--root, rhizome, root crown, etc--and then make a synthetic tag (like Leaf (anywhere) is now) for the ID filter that allowed users to just pick "underground" and see results that matched any of the above. My only hesitation on that would be that we'll rarely use them and they'll clutter up the dropdown menu for little gain. Otherwise it's the best solution. 

I have no strong feelings which of the two makes the most sense really. Renaming root is the easiest short-term solution but making more categories would be the most future-proof approach since you'll be adding the correct specific tags from the start.

**Comment by ddennism** [comment]
I think renaming "root" to any of the following:
"underground"
"root/rhizome"
"attached underground"

 would be ideal. There are important differences between roots and other subterranean plant organs, and these differences can be important for identifying galls (e.g. in goldenrods, *Eutreta* swellings are on roots; *Eurosta* swellings are on stems, mostly underground stems). But there's no harm in making the filter tag as broad as possible.

**Comment by Megachile** [comment]
Okay, I changed the name to "underground" and rewrote the definition: "Galls are located at or below the soil surface, on roots, rhizomes, underground stems, or other organs. May include galls that sometimes occur on stems slightly above soil surface."

**Comment by Megachile** [comment]
If we decide it's worth splitting later, we can always do that. There aren't that many root related galls so it wouldn't be the biggest issue to go through them and specify.
