### ISSUE TITLE
Host and Places Admin Changes & Additions

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#237]
Continuing the work started with #46...

## Place Admin
- [ ] create a Place admin page that allows the usual addition, modification, and deletion of data
- [ ] make sure that there is a way to manage the place hierarchy
- [ ] add the ability to map a Host species to a place

## Host Admin
- [x] add the ability to map a place to a Host species from the Host admin
- [ ] add the ability to do a lookup when creating a new Host. This will call into the new plants service that fronts the new plants DB that was built as part of #46
- [ ] names, aliases, range info should all be importable

Surely there will be more as I think it through more completely.

**Comment by jeffdc** [comment]
@megachile For now I am going to go with simple for adding/deleting places to hosts:

![Screen Shot 2021-07-28 at 10 21 22 AM](https://user-images.githubusercontent.com/39919/127339116-b3ab2c98-913a-4f4d-b618-94d257869243.png)

This will give us the ability to edit them in the short-term. The longer term solution of providing aggregations of places etc. is a lot more work. The DB structure that I created supports it but there is a good deal of work that will need to be done to fully implement it all. I think that for now I will focus on allowing work at the state/province level and not worry about a hierarchy/aggregations.

**Comment by Megachile** [comment]
Sounds good, I don't think the hierarchy is an urgent concern. The state level stuff is working very well so far and aside from the ability to fix issues with the data, which this will address, I don't think range is a priority necessarily anymore.
