### ISSUE TITLE
Alberta missing from region selection

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#247]
![Capture](https://user-images.githubusercontent.com/16893725/129298961-953825ab-7431-407f-9242-6f25270525de.PNG)

AB (The code for the Canadian province Alberta) seems to be missing from the region addition list.

**Comment by jeffdc** [comment]
It is already assigned. You can see it 5 to the left. I need to make that list sorted alphabetically so that it is easier to find things on it.

**Comment by licoriceleaf** [comment]
Sorry I should've noticed that.. was 2 AM where I was so my brain probably wasn’t up to speed

**Comment by jeffdc** [comment]
No problem. It is broken UI really. I have fixed it to sort the list alphabetically as well as to make it overall more user friendly. it will be part of the next deployment.
