### ISSUE TITLE
Alert users that that iNat See Also link should work for undescribed galls

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#250]
Now that #245 is operational, I think it would be good to find some way to indicate that this functionality exists. Part of the point of the update was to make it so we didn't have to manually write this link into each ID Notes, but right now I think it's easy to miss that it exists. Users will often (rightly) assume that these links will not work for undescribed species. I'm thinking something along the lines of, when Undescribed is checked, the other see also link icons are not even generated (we know they will not ever work) and the iNat link will have a note that reads something like "Unless noted otherwise in the ID Notes, observations of this gall are collected in an Observation Field linked here:"

**Comment by jeffdc** [comment]
This is definitely doable. I will add it into the current batch of work.
