### ISSUE TITLE
Image details sometimes brings up details for images that aren't selected

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#266]
On a gall page, if you click the copyright or image details buttons below the photo, they do not always fetch the info that corresponds to the photo currently displayed. This can lead to misleading copyright statements like this: 
![public domain](https://user-images.githubusercontent.com/69063635/134552767-1e43a392-56ea-4f5d-8314-eb898190e5c1.JPG)
On the image details page it is at least clear that you're looking at the details of a different image because it shows you the corresponding image. But it is of course annoying to ask for one piece of information and see another. 
![wrong details](https://user-images.githubusercontent.com/69063635/134555184-0f3e9bad-5596-440e-bcc5-f4f73ceaf696.JPG)

Sometimes, however, the photo doesn't load either, so there's no way to know that you're looking at the wrong info. 

![wrong details and no photo](https://user-images.githubusercontent.com/69063635/134555221-57e85b4e-db42-4a91-8b8f-fea477dd5ed4.JPG)

**Comment by jeffdc** [comment]
What browser are you using? In the past I have noticed some weirdness lie this with Firefox (my primary browser) but have not been able to replicate it with Chrome (the browser I use for testing and dev) or Safari (mainly on my phone).

**Comment by Megachile** [comment]
Firefox

**Comment by jeffdc** [comment]
Ugh. I am seeing the issue now with Safari on iOS. I will try and find time tomorrow to look at this.
