### ISSUE TITLE
Broken hyperlinks in "Random gall from our database"

### ISSUE THREAD

**Issue by licoriceleaf** [jeffdc/gallformers#269]
The hyperlinks on the Random gall from our database box on the homepage are broken. They always redirect to the wrong page, or to a non-existent page instead of linking to the page for the stated gall

https://user-images.githubusercontent.com/16893725/135553095-5c647c36-aa6e-46d5-acbf-a04b019d4fe7.mp4

.

**Comment by jeffdc** [comment]
Ah crap. I missed a commit before I built and deployed. Will fix it in the AM.
