### ISSUE TITLE
Make long source entries more manageable

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#291]
Right now, the only way to move from one source to the next is by scrolling to the source table at the bottom of the page. This can get somewhat annoying when there are a lot of sources of varying length, especially when some are very long. I've proposed in the past that it would be nice to have a way to tab between sources at the top as well as the bottom, but in lieu of that it would perhaps make sense to cap the initial loaded text from a given source and require clicking a button to manually expand it?

**Comment by jeffdc** [comment]
I have added a simple "tabber" at the top of the entry that allows you to cycle through the entries. It is not the best UX but I think it is sufficient for now.

https://user-images.githubusercontent.com/39919/141791154-10fa60a6-3b24-4c8b-84f4-6d5f35af37af.mov

**Comment by Megachile** [comment]
Beautiful, that's all I had in mind really.
