### ISSUE TITLE
Edit Source mapping shortcut link pencil seems to be gone

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#294]
I'm fairly sure I'm logged in and all of the other edit shortcut pencil links are present and functional, but the one for source mapping no longer appears on gall pages. 
![missing link](https://user-images.githubusercontent.com/69063635/143790513-d2a80725-f51f-42f8-b8c4-0fd419c44572.JPG)

**Comment by Megachile** [comment]
After the deployment I see a new shortcut to edit the currently selected source, but the shortcut we used to have to the species-source mapping page (subject of this issue) is still missing for me.

**Comment by jeffdc** [comment]
I misunderstood the issue. Do you want the new link to stay or should that link to the species-source mapping?

**Comment by Megachile** [comment]
I don't mind leaving the new one you added, I think that could be useful though pretty rarely so. I like that it links to the currently selected source rather than the default source. If you could do that with the source-species mapping instead I think that would be ideal. Otherwise we could have both the new and the old one.
