### ISSUE TITLE
Add explanatory note to Range maps on gall pages

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#301]
As it stands, the range map on each gall page is unexplained and would reasonably be interpreted as a positive statement that the gall is known to occur in every highlighted state. We should have a tooltip that explains the logic of the map in detail and possibly actually change the name always displayed from Range to something that conveys the uncertainty. Something like "Potential range" is closer but then of course if we do end up removing a place it doesn't quite match the meaning. Maybe something focusing explicitly on confidence level like "Inferred range" or "Likely range"?

The explanatory tooltip could say something like:

"For the vast majority of galls, observations are insufficient to infer the true range of the inducer. Regardless of confirmed observations, we assume that an inducer may at some point be found wherever its known hosts are present, so in most cases the range map is the sum of the ranges of known hosts. However, where sufficient information is available, some states and provinces may be removed from the map. If you find a gall in a place not listed on this map, please Contact Us [link]."

**Comment by Megachile** [comment]
An alternate/supplementary approach might be to display the gall page results as they are on the Gall/Host map page, with places where the host is present but the gall is not marked in a different color.

**Comment by Megachile** [comment]
Actually what might be ideal is to flip the logic of the map and allow the user to select states where we have confirmed observations and leave the others as a lower-confidence color.

**Comment by jeffdc** [comment]
I just saw this. Would you prefer your text or the one that I wrote?

**Comment by jeffdc** [comment]
I can not add a link to the tooltip as it is currently implemented.

**Comment by Megachile** [comment]
Either is fine
