### ISSUE TITLE
Add confirmed presence to map feature

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#302]
What might be ideal is to flip the logic of the map and allow the user to select states where we have confirmed observations and leave the others as a lower-confidence color. Each state could then take four values, something like: 

No host (white)
Host present, gall absent (red)
Host present, gall likely (light green)
Host present, gall confirmed (dark green)

The difference between the last two would show up on the Gall page and potentially on the ID filter if and when we implement a tiered likelihood rating on the filter results.

**Comment by jeffdc** [comment]
This is definitely doable but will require a new database table and a good bit of work to the underlying code. For what we have now I hacked it in using the existing table structures.

**Comment by Megachile** [comment]
Okay, well it's not a priority but I'll leave it up as something we might want in the future
