### ISSUE TITLE
Add copyright for All Rights Reserved (and CC?) images when viewed full size

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#307]
When a user clicks an image to view it full size, the link to the original is present, but the copyright info is only visible if the user exits full size and tabs to the image separately and clicks the i button. Can we add the copyright info onto that full screen view box too? At least in cases where it's an all-rights-reserved image?

**Comment by Megachile** [comment]
In full-size view, the Link to Original link is updating correctly when I move from one image to the next, but the new License stays at whichever it was for the first image opened. So eg now if I open a Weld image first and then scroll to [Alice's here ](https://www.gallformers.org/gall/2061) it shows that Alice's image is public domain. Also can you add the creator name on there as well? FTR this is specifically what Alice has been asking as a condition of using her images: 

"Yes, please make sure Copyright Alice Abela is visible with the image if my watermark is removed"

**Comment by jeffdc** [comment]
Argh. Tried to rush it and got what I deserved. Will fix it. Yes will add creator's name as well.

**Comment by jeffdc** [comment]
Fixed and deployed.
