### ISSUE TITLE
Aculops tetanothrix edit gall page freezing when any dropdown item is selected

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#308]
I imagine this is something to do with the huge number of hosts on this gall, since I haven't had the problem on any other gall. But on Aculops tetanothrix, any time I add or remove an item from any trait box, the page becomes totally unresponsive for a minute or so. Eventually it recovers but it is using 800-1500 MB of memory for that one tab and of course it's quite a pain to use. Reproduced in both Edge and Firefox.

**Comment by jeffdc** [comment]
Should be fixed once I get #318 resolved.
