### ISSUE TITLE
Still getting errors on inputting image details

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#354]
![uh ho](https://user-images.githubusercontent.com/69063635/180663556-854fad80-184f-4339-99e6-07284f05a06e.JPG)

**Comment by jeffdc** [comment]
I will look at this tonight. This is while adding image details?

**Comment by Megachile** [comment]
I had been assuming this was the same bug you fixed last night. I'll let you know if I run into it again but for now afaik it's good?
