### ISSUE TITLE
Trying to add undescribed gall but SUBMIT button remains inactive

### ISSUE THREAD

**Issue by NancyAsquith** [jeffdc/gallformers#363]
![image](https://user-images.githubusercontent.com/99035210/200154375-90d6690b-2987-4a83-9562-329f7f58e48e.png)

This happened once before, then I entered several unknown galls w/ no problems. I tried to paste a screenshot above, since Adam recommended sending you a screenshot when I had this problem before.

**Comment by Megachile** [comment]
This is because the species name was invalid (space where there should be a dash between witches and broom)
