### ISSUE TITLE
Add an optional page link to species-source mappings

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#37]
The "Map Species & Sources" page in Admin mode should have an additional optional text box beneath the Description where users can paste in a text link to the exact page where the description is found. This should not replicate the main reference link (eg if it's a pdf) already associated with the source, and should only be used in cases where the link is to a specific page (eg on BHL or HathiTrust). Once this information is entered, it should appear on the species page below the description, labelled in some way that indicates what it is (the link in Further Information should still link to the main source page).

**Comment by jeffdc** [comment]
@Megachile I made the change and deployed it. Let me know if it is working as you expected.

**Comment by jeffdc** [comment]
I assume that this is good. Will re-open if not.

**Comment by Megachile** [comment]
Yes this is exactly what I had in mind, thanks. My only further thought is that it would be good to explain further what kind of link should go here. So instead of just saying "External description link" there should also be a note explaining what this box is and is not for (otherwise people will just use it to duplicate the main reference link). My impulse is to festoon the whole website with clarifications and tooltips, so that we can at least try to keep things consistent once other users start entering info.

**Comment by jeffdc** [comment]
What do you want the text to say? I will make the change with the next deployment.

**Comment by Megachile** [comment]
Direct Link to Description Page (if available, eg at BHL or HathiTrust. Do not duplicate main source-level link or link to a pdf):

**Comment by jeffdc** [comment]
Fixed
