### ISSUE TITLE
Data quality indicators

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#38]
Edit: It seems ideal to find a way to make this quality data immediately obvious on the ID page, but in the meantime, we could make a separate page that tracks our progress in a table, as discussed in #39, with rows being host genera (and/or species?) and columns being traits (including one column that just indicates whether all galls known to be associated have been added), with a check mark to indicate the ones that have been filled comprehensively.

Original: Since the site is intended to be used before it will be "complete," we should have some way to indicate to users where our data is, to the best of our knowledge, complete, and where it is not. 

To that end, it would be useful to have a box to check on the admin page for a gall to indicate that every known source has been entered, which would trigger the appearance of a corresponding certificate somewhere on the gall's page (and a corresponding warning on pages for which this box has not been checked). 

Similarly, it would be good to have a box to check on the admin page of a host species or genus to indicate that every gall known to be associated with it has been entered, with a corresponding certificate/warning on the ID and Explore pages for those plants.

**Comment by jeffdc** [comment]
### Proposal

- [ ] add a data state field to the gall table: values (TBD)
- [ ] add a data state field to the host table: values: boolean (yes all galls entered; no not all galls entered)
- [ ] modify the main gall display page to show the state value in some way
- [ ] add logic to automatically compute this state based on known data. algorithm TBD - only applies to gall not host
- [ ] add the state field to the admin page for gall allowing an admin to override any computed state
- [ ] add the state field to the admin page for host allowing an admin to verify that all known galls for that host have been entered

**Comment by jeffdc** [comment]
I think that the data quality should be tied to the species level (gall/host). I am not entirely clear on what this means in terms of the reality of what is possible given the data that we will have.

**Comment by Megachile** [comment]
This all looks good except I don't see how any of these states state could be calculated algorithmically? The database has no way to know if we've entered every relevant source.

**Comment by jeffdc** [comment]
The data quality could be computed based on the non-presence of data. i.e., a gall with no sources is definitely not good data. We could also score for missing fields like, location, color, etc. if we wanted. We do not have to do this but it is possible.

**Comment by Megachile** [comment]
I see. That doesn't seem like a good idea given that it would mistakenly flag lots of things as complete when they were only partially complete. Might be useful at some point to be able to summon every species missing a certain value, though. But I would say that's a separate issue from what I'm trying to achieve here and not worth the time/effort now.

**Comment by Megachile** [comment]
We need to think a little more specifically about when we want to call something "done" and whether that differs for galls and hosts. There are two distinct things I have in mind here, and I'm slightly worried that they are not what other people might expect and might be confusing/conflicting. 

For hosts, I want to tell users that the ID filter function *for location/detachable* is comprehensive. That way, the filter tool is useful long before the other work is done. It's a goal we can achieve extremely quickly and easily. I sat down and did all of Weld's Q alba species in like an hour the other day. 

For each gall, I think the quality indicator should be a much higher bar to clear. I think it should mean we've added every known source with unique, relevant info, all of the traits and host relationships are updated to reflect that, and our ID notes tell them everything we know or suspect that isn't reflected in the other sources. IMO this should not necessarily mean that traits other than location/detachable are comprehensive.

First of all, do these thresholds make sense on their own? Any feedback/disagreement? 

Second, my fear is that people will assume that if a host is marked complete, that means each gall associated with it will be complete in the latter sense. So we need to make that really clear on the host page, maybe even use a different icon or something, to communicate that these two indicators mean different things.

**Comment by Megachile** [comment]
So if there are no comments, here's what I'd put. We can always change it later if people disagree.

Host: 
"All galls known to occur on this plant have been added to the database, and can be filtered by Location and Detachable. However, sources and images for galls associated with this host may be incomplete or absent, and other filters may not have been entered comprehensively or at all."

Gall:
"All sources containing unique information relevant to this gall have been added and are reflected in its associated data. However, filter criteria may not be comprehensive in every field."

**Comment by madeleineclaire** [comment]
Sorry I completely missed this the other day. Late to the show, but what you have put together above makes sense, Adam. I'd think in this field specifically (galls) that new information will become available constantly as so much is still undescribed, understudied, and unknown. I'd hope that most coming to this site for the purpose of seeking help ID'ing a gall would understand that and your messages are clear. Data/content will always be at the mercy of the speed in which it becomes available and known to those maintaining the database.
