### ISSUE TITLE
Externalize Image Hosting From the Main Site

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#4]
We do not want to host the images in the same place as the site itself. There are a number of reasons for this:

- ~Vercel (see #3) is not a good choice for hosting a lot of images~
- Images are large and will be the most expensive part of the hosting
- Images need to be cataloged, referenceable, etc
- Images will need to be web optimized and we will need multiple sizes for each image

Se how iNat handles this: https://www.inaturalist.org/photos/100582060

**Comment by jorgerasillo** [comment]
@jeffdc this seems optimal, note the "non-profit" organization blurb:

https://help.flickr.com/en_us/discounts-for-non-profit-organizations-rJio8cn7.

**Comment by jorgerasillo** [comment]
Found these guys too:
https://cloudinary.com/solutions/industries/cloudinary-for-nonprofits

**Comment by jeffdc** [comment]
Flickr has potential but it does not seem that SmugMug (the owner) is that interested in supporting the APIs. The docs and other info are all dated from prior to SmugMug's acquisition more than 2 years ago. The "best" API wrapper for node is this one: https://github.com/flickr/flickr-sdk  It is still maintained it seems. 

Cloudinary looks to be heavily geared towards basic website (marketing) image and media.

Given the importance of the images to the overall site, I think we will need to have them in-house.

**Comment by jeffdc** [comment]
My current thinking is putting a basic layer on top of this: https://www.digitalocean.com/products/spaces/
