### ISSUE TITLE
Detachable field should be multiselect

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#40]
Edit: Because some galls are integral in some phases and partly detachable in others, we need to be able to select yes, no, or yes and no for a given gall. It seems like the simplest way to achieve this would be to make "Detachable" a multi-select field like Location is now. This would also obviate the checkbox bug noted below. 

Original: 
Eg: I load the page for Aceria elongata and it correctly shows "Detachable: no." Then I open the admin page for that species and the box is checked for yes. If I make a change elsewhere and submit, that changes the detachable status to yes. Easy to overlook and change the data by mistake. In species that are listed as "Detachable: yes" on their gall page, the box loads as checked on the admin page as well, though it's correct in that case.

**Comment by Megachile** [comment]
@jeffdc it occurred to us that instead of fixing this bug, we should just change the nature of this field. There are species that can be integral early in the season and develop a detachable part later in the season ([eg Celticecis expulsa](https://www.inaturalist.org/guide_taxa/1299367)), so some galls need to be associated with both yes and no, OR we need to add a third category that somehow communicates that special kind of detachability (although that third condition may not be obvious in some life stages, so even then we'd still need to be able to assign multiple values to a given gall). Either way the check box isn't going to cut it. Sorry I didn't catch this earlier.

**Comment by jeffdc** [comment]
No problem. Re-write this issue to encompass what is needed.

**Comment by ahiatt14** [comment]
@jeffdc Sorry I dragged my feet on this one. I know I'll frick something up if I try to do a schema change myself. What's the protocol/order of operations for deploying a code change + schema update? I'll probably just try accomplishing this on my local repo using the documentation you provided and update the PR and we can go from there

**Comment by jeffdc** [comment]
What schema change is needed? It is already an integer so provides flexibility.

I have a bunch of schema changes that will be needed upcoming, see #72, we could make a change as part of that if we want to.

**Comment by jeffdc** [comment]
What are the values for detachable?

It sounds like they are (at least):

- yes
- no
- both (not sure how to word this
- none/unassigned

**Comment by Megachile** [comment]
I was thinking we would keep it as simple as possible

- Yes
- No
- (none selected)

If it's both, then you just select both. That's why I want it to be a multiselect. 

Does that seem good to you?

**Comment by jeffdc** [comment]
Selecting both (multiselect) requires that I add two new tables (to allow the many-to-many) relationships so it is a lot more work to do. I am already doing that for the other fields, shape, color, etc. so I can do it and now is the time to do so if that is what we want. However, I think that having a multiselect field with the options yes and no is really weird. People's expectations for Yes/No are that they are exclusive. I would recommend that we re-think this field. Possibilities:

- Rename Yes / No to something else
- Disallow multiselect and give options like I suggested: yes, no, both, none

Maybe there are other ways?

**Comment by Megachile** [comment]
I don't understand how a third "both" option would work. I must be misunderstanding what you mean? 

What I think you're saying is that the admin would select "both", which would mean that gall would only appear if the ID user selected "both." But how would an ID user know to do that? They're looking at a gall that is either detachable or not, so they select the one they think they see. They may not know that later in the season it becomes detachable (or vice versa). 

The user's expectation is that they are mutually exclusive, so it's on the user end that we have to only present those two options. In order to make that possible, we have to account for the fact that they are not actually exclusive on the admin end. 

The only way I can imagine your suggestion working is that you could let admin users select yes/no/both and then have the ID user filter pull "both" entries whether they select yes or no. That would save a click for the admin side (and let you keep it as a single select field) but it would complicate the other side so idk if it's worth it. 

We could rename yes/no to "integral/detachable" but IMO those are synonymous with the existing terms. Giving the impression these are technical terms might make people think more carefully about them, which has some pros and cons, but it wouldn't change the underlying data structure at all, so idk if it would address your concerns and it wouldn't save you any work.

**Comment by jeffdc** [comment]
My biggest concern is that putting "yes" or "no" up on the screen for a user to see implies that it is a 2 choice option. The data structure and the admin side, I am not as concerned about. We can make those work however we need to.

Your 4th paragraph gets to what I was suggesting. Show the user Yes/No/None on the ID screen filters like we do now. Then if a species is assigned "both" then it would match anything but None. On the gall detail screen we would show "Both" with some kind of explanation that "Both" means that it transitions from one to the other not that it is quantum in nature.

**Comment by Megachile** [comment]
Can you give me an example of a case where it would be bad to present the user the implication that it's a two choice option? I think it is, within the context of an individual observation.

**Comment by jeffdc** [comment]
If you search on Amazon and are a Prime member you get a screen like this:

![Screen Shot 2021-02-13 at 9 37 42 PM](https://user-images.githubusercontent.com/39919/107866995-dc6e9c00-6e44-11eb-83f5-d0148f699dd1.png)


Now imagine if it were instead like this:

![Screen Shot 2021-02-13 at 9 43 58 PM](https://user-images.githubusercontent.com/39919/107867002-ea242180-6e44-11eb-9e76-d34a864ea59d.png)

Or even more strangely:

![Screen Shot 2021-02-13 at 9 47 41 PM](https://user-images.githubusercontent.com/39919/107867048-38d1bb80-6e45-11eb-8ab6-9dfbdd77b8f7.png)

This is confusing UX and is what I am concerned about.

**Comment by madeleineclaire** [comment]
As a novice in gall identification, I would likely come to this site with a specific photo/visual of a gall I am looking to identify. In that moment the gall is either in a detachable state or it is not. While it is true that some galls can start out one way and end up another way, at this point in my journey I don't know that. I am trying to figure out what I'm looking at and can only give my input based off the current state of the gall I am observing. 

That being said, what would probably be the most intuitive to me would be a Yes or No.  What Jeff mentions here makes sense and sounds like would cover me in the majority of scenarios: "Show the user Yes/No/None on the ID screen filters like we do now. Then if a species is assigned "both" then it would match anything but None. On the gall detail screen we would show "Both" with some kind of explanation that "Both" means that it transitions from one to the other not that it is quantum in nature."

**Comment by ahiatt14** [comment]
> 
> 
> As a novice in gall identification, I would likely come to this site with a specific photo/visual of a gall I am looking to identify. In that moment the gall is either in a detachable state or it is not. While it is true that some galls can start out one way and end up another way, at this point in my journey I don't know that. I am trying to figure out what I'm looking at and can only give my input based off the current state of the gall I am observing.
> 
> That being said, what would probably be the most intuitive to me would be a Yes or No. What Jeff mentions here makes sense and sounds like would cover me in the majority of scenarios: "Show the user Yes/No/None on the ID screen filters like we do now. Then if a species is assigned "both" then it would match anything but None. On the gall detail screen we would show "Both" with some kind of explanation that "Both" means that it transitions from one to the other not that it is quantum in nature."

This explanation makes the most sense to me.

> 
> 
> What schema change is needed? It is already an integer so provides flexibility.
> 
> I have a bunch of schema changes that will be needed upcoming, see #72, we could make a change as part of that if we want to.

Ahh. So we map ints to an arbitrary set of hardcoded values elsewhere, like an enum? In that case nevermind about the schema change. Should be simple enough then.

**Comment by madeleineclaire** [comment]
Can we program an easter egg where if you select 'Both' that it takes you a single option named Schrodinger's Gall and is just a picture of a box with an annotation: Detachable: BOTH?

(I'm joking. Sorta.)

**Comment by Megachile** [comment]
@jeffdc  I think I see what you mean now? That leaving the "yes" box unchecked should be the same as having the no box checked and vice versa? I think replacing yes/no with integral/detachable would solve that confusion adequately--do you agree? Otherwise I think we're on the same page with this: 

"Show the user Yes/No/None on the ID screen filters like we do now. Then if a species is assigned "both" then it would match anything but None. On the gall detail screen we would show "Both" with some kind of explanation that "Both" means that it transitions from one to the other not that it is quantum in nature."

So is this a good solution? 

- Admin Add/Edit Gallformers has a single select Detachability field with options "detachable", "integral", "both" or can be left blank
- ID page will have a filter called Detachability which can be left blank or one of two options can be selected. Detachable pulls up all galls labelled either Detachable or Both, etc. 
- Gall pages for galls tagged Both will have an explanation of what that means
- Detachable terms will be explained on the Filter term FAQ as well

I would have thought that would be a lot more work for you than just making it a multiselect but it amounts to the same result so if it is easier then it seems fine to me.

**Comment by jeffdc** [comment]
I am already doing a bunch of work to deal with making those other fields multi-select so I am already in this code. Believe it or not all of these changes stemmed from #83.

This makes sense and is I a solid approach.

**Comment by jeffdc** [comment]
Here is what the Admin side is looking like now. This includes making the other fields multiselect as in #77 
![Screen Shot 2021-02-14 at 11 07 54 AM](https://user-images.githubusercontent.com/39919/107882008-06f83d80-6eb5-11eb-83c7-019da0fe07e8.png)

and here is the user-facing screen if it is "Both":
![Screen Shot 2021-02-14 at 11 15 38 AM](https://user-images.githubusercontent.com/39919/107882204-fd230a00-6eb5-11eb-8df2-2a624469d7da.png)

**Comment by Megachile** [comment]
Wow, that was fast! Looks great to me.

**Comment by jeffdc** [comment]
I got iced in yesterday so could not leave the house so I had time! I opened a PR for these changes #85. I have done some basic local testing and it seems good. I will deploy it today. However I think that we need to look at all of the current galls and re-assess their detachable state as it looks like they were defaulting to integral which is not what I had thought.

I am going to have to run a migration to covert the data over to the new forms so now is the time to look at this. Here is a table of all the galls currently in the DB and what their detachable state is (0 - integral; 1 - detachable):

```
Acalitus essigi	0
Acalitus ferruginea	0
Acalitus gossypii	0
Acalitus phloeocoptes	0
Aceria aloinis	0
Aceria annonae	0
Aceria baccharipha	0
Aceria brachytarsa	0
Aceria breakeyi	0
Aceria calaceris	0
Aceria caliberberis	0
Aceria caulis	0
Aceria ceanothi	0
Aceria celtis	0
Aceria cephalanthi	0
Aceria chondrillae	0
Aceria cinereae	0
Aceria cynodoniensis	0
Aceria dina	0
Aceria elongata	0
Aceria erinea	0
Aceria eucricotes	0
Aceria fraxini	0
Aceria fraxiniflora	0
Aceria granati	0
Aceria kuko	0
Aceria lepidosparti	0
Aceria litchii	0
Aceria mackiei	0
Aceria major	0
Aceria modesta	0
Aceria myriadeum	0
Aceria negundi	0
Aceria neoessigi	0
Aceria nyssae	0
Aceria parapopuli	0
Aceria parulmi	0
Aceria sandorici	0
Aceria sheldoni	0
Aceria spermaphaga	0
Aceria spicati	0
Aceria theospyri	0
Acericecis ocellaris	0
Acraspis quercushirta	0
Aculops aenigma	0
Aculops rhois	0
Aculops tetanothrix	0
Aculus minutissimus	0
Aculus quinquilobus	0
Amphibolips confluenta	0
Amphibolips globulus	0
Amphibolips quercuscoelebs	0
Amphibolips quercusinanis	0
Amphibolips quercusostensackenii	0
Amphibolips quercusspongifica	0
Andricus apiarium	1
Andricus femoratus	1
Andricus flavohirtus	0
Andricus ignotus	0
Andricus pattoni	0
Andricus quercusstrobilanus	0
Andricus robustus	0
Andricus weldi	1
Aprostocetus smilax	0
Asphondylia borrichiae	0
Asteromyia carbonifera	0
Asteromyia euthamiae	0
Asteromyia modesta	0
Atrusca quercuscentricola	0
Belonocnema fossoria	1
Belonocnema kinseyi	1
Blaesodiplosis canadensis	0
Blaesodiplosis crataegifolia	0
Blaesodiplosis undescribed	0
Blaesodiplosis venae	0
Callirhytis furva	0
Callirhytis gemmiformis	0
Callirhytis infuscata	0
Callirhytis lanata	0
Callirhytis piperoides	0
Callirhytis quercuspunctata	0
Callirhytis seminosa	0
Callirhytis tubicola	0
Callirhytis vaccinii	0
Caryomyia tubicola	0
Cecidophyes naulti	0
Cenalox conyssae	0
Cenalox nyssae	0
Colomerus vitis	0
Contarinia (undescribed)	1
Contarinia negundinis	0
Cryptophyllaspis liquidambaris	1
Ctenodactylomyia watsoni	0
Dasineura aceris	0
Dasineura communis	0
Dasineura crataegibedeguar	0
Dasineura rileyana	0
Disholcaspis bassetti	0
Disholcaspis globosa	0
Disholcaspis quercusmamma	0
Dryocosmus deciduus	0
Eriophyes aceris	0
Eriophyes adenostomae	0
Eriophyes cerasicrumena	0
Eriophyes emarginatae	0
Eriophyes helicantyx	0
Eriophyes laevis	0
Eriophyes paraspiraeae	0
Eriophyes pyri	0
Eriophyes sorbi	0
Eriophyes tiliae	0
Leptocybe invasa	0
Neuroterus laurifoliae	0
Neuroterus saltarius	0
Neuroterus tantulus	1
Phyllocoptes didelphis	0
Phyllocoptes triacis	0
Phytoptus avellanae	0
Podapion gallicola	0
Proteoteras aesculana	0
Proteoteras willingana	0
Rabdophaga rosacea	0
Rhyncaphytoptus magnificus	0
Rhytisma acerinum	0
Rhytisma americanum	0
Rhytisma punctatum	0
Stephomyia eugeniae	0
Synanthedon acerni	0
Synanthedon acerrubri	0
Trisetacus alborum	0
Trisetacus batonrougei	0
Trisetacus campnodus	0
Trisetacus floridanus	0
Trisetacus gemmavitians	0
Trisetacus neoquadrisetus	0
Trisetacus pseudotsugae	0
Trisetacus quadrisetus	0
Trisetacus sequoiae	0
Undescribed undescribed	1
Vasates aceriscrumena	0
Vasates oldfieldi	0
Vasates quadripedes	0
Xanthoteras ornatum	0
Xylotrechus aceris	0
Zopheroteras cuneatum	1
Zopheroteras hubbardi	0
```

What I need is to know all of the ones that I should change and what I should change them to.

**Comment by Megachile** [comment]
I notice a lot of the cynipid galls here are wrong. These are the ones I notice now but may not be perfect--I assume it will be possible to edit them as we actually incorporate the literature and do final checks etc?

Should be detachable:
53
43
48
39	
40	
42	
71
47	
52
45
62
44
73
68
70
50
49
51
55
60

Should be both:
54 
30
41

**Comment by jeffdc** [comment]
I will update these when I run the DB migration. We will be able to edit any and all after this as well via the normal mechanisms I just wanted to get these fixed to start with since I am migrating the data.
