### ISSUE TITLE
Add species name and host list boxes to Map Species and Sources 

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#41]
The species page includes descriptions for a taxon regardless of its name. It would be useful to know which name was actually used for the species in a given source, by adding a box for this in the Map Species and Sources admin page. On the species page, this could display above the description in a parenthetical eg " (As Eriophyes aceris) " on the Aceria aceris page. 

The species page has a comprehensive list of up-to-date host associations from the gall or host-gall admin pages, but it would be good to be able to track the sources that these associations were taken from, as well as to indicate associations that were listed in a source but which we have delisted. So the Map Species and Sources admin page should also have a box to list the hosts associated with a gallformer, which would be listed above the description with a note/tooltip indicating they may not be valid if they disagree with the topline associations.

**Comment by Megachile** [comment]
In the short term my priority is to simply have these as boxes to be filled so I can start entering the data, but in the long term (and maybe this is easiest to add or plan for while it's built so putting it out there now) I think both of these boxes should automatically populate the synonym and host association boxes for the gall in question. The site should check every inputted name or host against the existing list and add it if it doesn't already appear. 

For hosts, however, we need to provide a way for users entering data to indicate that the host is not a valid association. This could be a confirmation box along the lines of "This host isn't already associated with this species. Is it a currently valid association?" 

And, I think most helpfully, we should have some way of visually indicating that a host association is not valid when you view that entry. Strikethrough, font color, idk.

**Comment by Megachile** [comment]
While we're doing this might be a good time to add some text to the Description prompt. My hope is to open up the Admin end to a few other users soon and get their feedback and I'd like to do what I can to clarify some consistent expectations within the site for that if possible. This is what I have in mind now but open to suggestions:

Description: (All text from the source concerning the gall's physical traits, place and time of confirmed observations, other phenological info, and taxonomic revisions. Do not include anatomical descriptions of arthropods.)

**Comment by jeffdc** [comment]
I am thinking that this would be handled something like this on the admin side:

- From the current Species-Source mapping screen a button would appear if the mapping is between a Gall and a Source (not for a Host-Source)
- the button would open a Modal window (like the new Image Admin edit modal)
- the modal would pre-populate with the known gall-host mappings in a table
- a new mapping could be added with the option to mark it as invalid
    - if the new mapping is NOT marked as invalid it will be saves as a normal gall-host mapping
    - if it is marked as invalid then it will not show as a normal gall-host mapping
- existing mappings could be deleted if the host relationship is not in the source (@megachile do we want/need this?)

Once we get this nailed down I will think about the display side on the Gall page.

**Comment by Megachile** [comment]
So if I understand this correctly, the Alias field would be prepopulated with entries from the Synonym field if any had been added, as well as the valid name, and you'd pick one when you mapped the source? That makes sense to me and while it would obviously be most convenient to be able to add a new one right there, it would be fine to have to go back and add it through the gall page as well, especially for the time being.

For host mappings, you're implying that we would load all of the known associations by default, then ask the user to add or subtract the ones listed in each source? That seems good to me, especially for galls that have many hosts, but it would definitely mean we need to allow users to delete a mapping not included in a source (that's the whole point of this after all). I am slightly afraid users will neglect to remove ones that aren't listed in a given source. Could we prepopulate them but make it so you have to actively click each one to confirm? The way you propose handling invalid host relationships seems good to me.

**Comment by Megachile** [comment]
Okay, I came up with a proposal for low-tech way to handle this. All text provisional, first draft. 

The user chooses a set of filters and gets either no results, prompting the system to display this message: 

> It’s possible there are no described species that fit this set of traits and your gall is undescribed. However, before giving up, try altering your filter choices (link to tips). 

or some results, which are displayed along with this message: 

> If none of these results match your gall, you may have found an undescribed species. However, before concluding that your gall is not in the database, try altering your filter choices (link to tips). 

The link would take the user to a page containing text like this: 

> The host, location, and detachable filters are comprehensive to the best of our knowledge for every host genus listed here (link to list). If you’re not finding a match, try using only these three filters before you give up. Common issues using these filters include: 
> wrong host ID (try moving up to the genus level or checking your second or third guesses)
> Whether a gall is “Between veins” or “on leaf veins” can occasionally be ambiguous or misleading; try choosing the opposite or avoiding these terms entirely
> Bud galls are often mistaken for stem galls
> A gall looks detachable but is not (or vice versa); check the results for the opposite option
> 
> Other traits, including color, walls, cells, alignment, shape, and texture, are added only comprehensively for particular host genera (link to list). In other genera they may be applied incompletely or not at all. Check the filter glossary (link to #62) to make sure you’re applying the terms consistently with our usage.
> 
> There is also the possibility that your gall is not a gall; see our FAQ page on structures commonly mistaken for galls (link to #60).  

The linked list would be a table that serves the function of #38, with rows being host genera and columns being traits, with a check mark to indicate the ones that were added comprehensively. 

How does that sound?

**Comment by jeffdc** [comment]
I like the idea of forcing the user to opt-in from the prepopulated list.

Yes we will have to make it so that you can add a mapping from this screen.

**Comment by jeffdc** [comment]
I am going to start work on this one. It will also incorporate #72 and all of its downstream impacts:

Impacted: #38, #44, #45, #46, #47, #61, #71

Generally #71 addresses: #47, #61

This is going to take a awhile to complete and will require a lot of testing. Once I start digging in I will have a better idea of ust how long it will take.

**Comment by Megachile** [comment]
Sounds great; let us know if there's anything we can do to lighten the load or help out testing etc along the way.

**Comment by jeffdc** [comment]
Once I get it to a stable place maybe @ahiatt14 can pull the branch down and run locally and you all can test that way.

**Comment by Megachile** [comment]
Adding some more source data, I'm running into an issue we maybe need to think about. 
In the Amrine catalog, each deprecated synonym has its own entry, with its own list of prior synonyms, description, and host associations. That can get pretty messy, especially when more than one species is synonymized into one, and each of those older species had several synonyms, etc. Eg look at this one: https://www.gallformers.org/gall/534

I don't know if this scenario is common enough to develop a whole system to handle it (it would require allowing multiple entries for a given gall-source relationship, and assigning the hosts and synonyms to those individually). It's probably fine to just paste it into one box like this. It'll look a lot better once we get line breaks in there. 

But a much more common case is when a new description synonymizes multiple previous names, and I think it would be useful to have the ability to assign these deprecated synonyms to a given gall-source mapping as well as a given name. To achieve that, the alias mapping field would be like the proposed host mapping field, with the ability to list multiple entries and mark some of them as invalid.  Otherwise we are going to end up with a lot of unattributed synonyms (though at the moment those aren't even displayed publicly anyway), which IMO undermines part of the point of associating the synonyms with their sources in the first place. Thoughts? Not sure how much harder that makes your life or how worthwhile/necessary it is, but it is my impulse to collect and present this info if possible.
