### ISSUE TITLE
Description box in Map Species & Sources does not preserve line breaks

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#42]
Not a big deal but it doesn't seem possible to separate paragraphs with line breaks in the description entries.

**Comment by jeffdc** [comment]
The good news is that it saves the line breaks it is just no rendering them. I will look into fixing it.

**Comment by ahiatt14** [comment]
Looks like there's no white-space property set in the stylesheet(s) to respect \\n. I woulda guessed Bootstrap did that by default but apparently not. I personally don't have a preference as far as where to put the styling. I could create a "white-space-pre-wrap" utility class in pages/style.css and use that on the selectedSource description component in pages/gall/[id]/index.tsx, or just do direct inline styling on it. Or we could set a global css white space rule for respecting tabs/linebreaks. I'll defer to you @jeffdc on that code style choice

**Comment by jeffdc** [comment]
I like the idea of adding the style to the pages/style.css. It is currently under-used as I am mostly a back-end dev hacking on the front-end. :)

**Comment by ahiatt14** [comment]
My styling and css management experience is pretty limited too. I've never been perfectly happy where I ended up with juggling all the concerns there. I'm a little surprised Bootstrap's utility library isn't more robust but I'm too ignorant of the conventions around text styling to judge
