### ISSUE TITLE
How to handle gallformers with multiple distinct galls

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#44]
In the airtable database, I made galls and gallformer species distinct because some species form different galls in different conditions (asexual or sexual, on different hosts, etc). We should have a systematic way to note sexual/asexual generation galls for cynipids in any case, but in a broader sense, can we make multiple "galls" for the same species? Somewhat related to the undescribed species question--if we had a good way to name galls without taxonomic names of the gallformers this wouldn't be an issue, but otherwise we end up with duplicate names for distinct entries.

**Comment by Megachile** [comment]
The solution for undescribed species [proposed here](https://github.com/jeffdc/gallformers/issues/45) might also suggest a way to handle this problem. Add a boolean checkbox which allows the user to split a gall into two, allow a third name element to disambiguate them (eg Andricus utriculus (sexgen) or Andricus utriculus (asexual) or whatever), and assign a distinct set of host associations and other traits to each.

**Comment by jeffdc** [comment]
It seems like to solve this we will need to separate galls from the gallformers. I had not realized this when I designed the initial DB Schema. This is a relatively big piece of work, not in complexity but in amount of changes needed. Before embarking on this we need to nail down other issues that are in the same general area, like #45, #46, and #47. All of these require db changes in the same areas (species, gall, host). We also want to make sure that we have a solid understanding of what we want this to look like and it should all behave when it is done.

### Current State

There is a species table that holds common species level information that is shared by hosts and gallformers. There is a gall table that holds info specific to gallformers (locations, textures, colors, etc.). Currently the relationship between species and gall is many-to-many with the expectation that no single species would map to >1 gall.

### Proposal:

- [ ]  modify the gall table to add fields ... TBD
- [ ] change implementation logic to allow for more than one gall per species
- [ ] redesign the Gall display UI to handle this, details TBD
- [ ] redesign search results and ID screen to handle this, details TBD

**Comment by Megachile** [comment]
We could also make generation a filter field, only applied to cynipids, which would allow us to filter by generation in the ID results. But that doesn't seem particularly useful to me. Maybe something that could have value in the long run though, for data analysis or something.

**Comment by jeffdc** [comment]
I am convinced that we do not need to implement much (if anything) for this. The naming convention should cover everything. The duplication stuff we are talking about on #106 will make it easier.

**Comment by Megachile** [comment]
You told me you already implemented something on the database side just not the UI--what was the db change you made?

**Comment by jeffdc** [comment]
The DB change was to add an intermediate table between species and gall. This allows, if we want, many species to be associated to many galls. Previously it was 1-1. Currently all of the data is still 1-1.

**Comment by Megachile** [comment]
That's what I thought. I do think that it would be good to have the data 1-many in theory, but I think the only way that would really become relevant would be for like, data analysis? Eg if we were going to pull our dataset and run a host phylogeny, we might not want to double-count generations of the same species. There are probably relatively easy ways to solve that issue in that case tho too, using the fact that the genus-species name will be the same. But as discussed, from the user perspective looking for info on one species, the search function and ID filter will handle those use cases just fine. If there's an easily implementable way to make those mappings happen, great, if not, I think we can just close this?

**Comment by Megachile** [comment]
One reason it might be nice to combine the two generations is that otherwise any taxonomic changes have to be duplicated. But IMO it's better to keep these separate because the two different generations do actually have different lists of synonyms, and even though they technically do apply to the whole combined species, I think that isn't how we should handle it.

**Comment by Megachile** [comment]
Callirhytis quercusfutilis is now entered using the naming convention method, if anyone wants to see what that looks like in action.

**Comment by jeffdc** [comment]
This looks good to me and I agree we close this one.
