### ISSUE TITLE
Mechanism For Handling Undescribed Species

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#45]
Currently there is no reasonable way in the system to handle species that are undescribed (and thus unnamed).

To rectify this we will:

- Add an undescribed boolean value to a gall that can be set by an Admin
- If a gall is marked as undescribed then:
   -  the Genus can be assigned while the species left blank
   - the Genus can be left blank and then the species must also be blank
   - a placeholder name field must be filled in with some unique name to identify the gall in place of the usual 'Genus species'
   - when it is unmarked as undescribed, then both the Genus and species must be provided

The idea of the placeholder needs more thought.

**Comment by Megachile** [comment]
I think this sounds good. The two solutions we've already come up with for undescribed species are numbering (eg Aceria n. sp. 2), which would be annoying to use when mapping, and placeholder "common" names, as we've been using to tag the Similar Observation Sets on iNat (eg Postoak_KernelGall). The latter seems much more usable. It might be good to have some kind of protocol for generating those--the ones I've applied on iNat are all over the place.

**Comment by jeffdc** [comment]
To try and help consistency ee could add code to suggest a placeholder name based on available data. e.g., an undescribed gall on Q. alba that is known to be in genus Andricus could be, Andricus alba-[TODO] where [TODO] is either a random noun or some user provided string. If the genus is not known the same idea would apply but without the genus name.

**Comment by Megachile** [comment]
That seems reasonable to me. So if the genus is known we could say Contarinia negundo-beadgall and if it was not we would just leave the genus off and call it negundo-beadgall?

**Comment by jeffdc** [comment]
Something like that yeah. I think that the key here is that we provide a reasonable and easy path to a consistent naming scheme that can be overridden but is more work to override than to not.

**Comment by Megachile** [comment]
Your change on this is going to allow species names to include dashes, right? I just went to add the most common gall in the US, Gymnosporangium juniperi-virginianae, and it won't accept it because it has a dash in it.

**Comment by jeffdc** [comment]
Oh I did not know that dashes were not allowed! I will roll a quick change out with this fixed and the image compression change that we talked about in Slack.

**Comment by Megachile** [comment]
Can I start adding undescribed species that have known genera yet (eg something like "Polystepha conegall"), and then tag them undescribed later? Or would it be better to wait?

**Comment by jeffdc** [comment]
Let's wait. I will work on this next, as soon as we get this other one, #86 tested and deployed.

**Comment by Megachile** [comment]
That's what I figured; I'll wait.

**Comment by Megachile** [comment]
What should/could we do about undescribed gall inducers at the genus or even family level? For instance, we know that most species in the genus Blaesodiplosis are undescribed. We could try to look at iNat observations and create likely species by gall morphology/host. Or we could just make one collective page that was something like "Blaesodiplosis various" (tagged undescribed) and cover them all together. Seems like that would fulfill our intent well (presenting all available info in the form useful for IDing galls) and work easily within the system already proposed. The only qualm is that otherwise the db is always one page per gall; idk if that really matters though. But I thought I'd bring it up before you implement in case it sparks any other ideas/adjustments.

**Comment by jeffdc** [comment]
To start with let's make sure we have the possible scenarios understood. As I understand it:

Host(s) Known:

- Unknown genus (Family possibly also unknown)
- Known genus (therefore Family known)
- There may be a collection of similar galls e.g., QAlba-bead-galls that could be >1 species even of different Genus/Family

Host(s) Unknown:

- I do not think that we want to try and handle this case

Assuming what I wrote above is correct, here are my thoughts on how we should handle all of this:

### In the Gall Admin:

- Add a Button "Add Undescribed"
    - This initiates a workflow:
        1. Is this Genus known? If yes then choose it. If no then assign to the "special" genus "Unknown"
        2. Is the Family known? Choose it. (Must be if Genus is known) If not then special family "Unknown"
        3. Provide a short description e.g., red-bead-gall
        4. Provide type host short name, e.g., alba or Qalba
        5. This will produce a final name something like: Unknown alba-red-bead-gall or Unknown-lobatae-stem-gall
        6. The name can be changed by the admin, but it must be unique
- Add an Undescribed checkbox to the Gall admin page - this will be checked and read-only if the Genus/Family is assigned to "Unknown". If the genus is known, then it will be editable and it is up to the admin to make sure it is correct

### On the Main Gall Page

- Provide some visual indicator that the species is undescribed - details TODO

### Elsewhere

- The  Unknown Family and Genus will behave as with other Family or Genus display (but will not be editable by Admins)
- Since we now will have the undescribed checkbox value assigned to the galls we could provide an Undescribed flag on the ID screen. Could also create a browse Undescribed galls page (somewhat like the Browse Gall page)

None of this precludes what you have proposed RE creating a "Blaesodiplosis various" placeholder. 

I also want to keep the management of unknowns within the current gall admin page. This makes sure that we are collecting all of the same data and when it hopefully becomes known it is as simple as updating the name, unchecking the undescribed box, and adding the new source.

**Comment by Megachile** [comment]
This all sounds great, especially the "Browse undescribed" or similar. I don't think I have any comments at the moment. I agree that making pages for unknown galls with unknown hosts would be nigh-useless within the mission of our site.

**Comment by jeffdc** [comment]
Here is what I have so far for the creation step. The name field is auto-computed:
![Screen Shot 2021-03-25 at 2 56 18 PM](https://user-images.githubusercontent.com/39919/112528508-9b8a7100-8d7a-11eb-8ad5-b5fd7df0fb23.png)

and
![Screen Shot 2021-03-25 at 2 58 39 PM](https://user-images.githubusercontent.com/39919/112528516-9e856180-8d7a-11eb-83b2-f32f64c4fedf.png)

You can probably divine the algorithm that I am using to compute the name. Any thoughts?

**Comment by Megachile** [comment]
Will this automatically fill in the host on the gall page as well? Otherwise looks good (adjectives is misspelled).

**Comment by jeffdc** [comment]
Yes it will transfer over all of this stuff to the main Gall admin page once you click Done.

**Comment by jeffdc** [comment]
I have found a potential hole in this plan:

All Genera must have a parent Family. The Genus could be unknown and that Family could be Unknown or it could be some other known Family. This means that we could in theory have n+1 (where n is the number of families) taxonomy entries named 'Unknown'. From the programmatic side this is not an issue since they are all distinct. However, it will create a lot of potential noise in the UI, especially I think with Search.

A quick example to make it clear:

- Gall 1: Unknown q-alba-red-bead-gall -- Family Unknown
- Gall 2: Unknown q-alba-red-petiole-gall -- Family Cynipidae 
- Gall 3: Unknown a-negundo-blister-gall  -- Family Eriophyidae

That is a total of 4 Unknowns in the taxonomy.

A simple solution that I do not think we want, is that we make it so that if the Genus is unknown then then the Family is also unknown. Thus there will only ever be 2 Unknowns in the taxonomy, 1 Genus and 1 Family.

Alternatively we allow all the Unknowns in the taxonomy and come up with a way to condense them when displaying.

The 1st solution is super easy, the 2nd is likely a good amount of work.

Maybe there are other ways then these two????

**Comment by jeffdc** [comment]
Writing all of this down and thinking a bit more maybe this is not an issue at all. Currently there is nowhere that we display a list of just Genera and I do not think that we will ever have that. So maybe a false alarm? 

@Megachile any thoughts?

**Comment by Megachile** [comment]
IMO the search problem is not a big deal at the moment; we can think about how to build a different way to present undescribed species all together later if we want. It seems like the only problem that actually *needs* to be solved here is in the admin end. I agree that it could cause problems if users are trying to guess which of a dozen Unknown entries to pick, maybe not aware that these are distinct specific entities etc. 

Could we solve that the same way you handled #98 ? That didn't seem to be too onerous to implement. So ie if you typed Unknown the dropdown would show something like:

Unknown (Eriophyidae)
Unknown (Cynipidae) 
Unknown (Psyllidae)

It wouldn't hurt to show this info for other genera too. 

Or, could you just suppress the dropdown menu for genus completely when the user has not selected "part of a known genus" ?

**Comment by jeffdc** [comment]
Here is what I did. On the undescribed sp creation screen:

- if Unknown is selected for the genus by ticking the checkbox - thus eliminating the need to figure out which one then:
    - the Family is auto-selected to Unknown but can be changed to anything
    - the Genus is set to Unknown and read-only
- If Unknown is not selected for the genus but some other genus is, then the Family is auto-filled and made read-only 

![Screen Shot 2021-03-27 at 6 09 57 PM](https://user-images.githubusercontent.com/39919/112736248-a9c9c000-8f27-11eb-8101-721050a7d72c.png)


![Screen Shot 2021-03-27 at 6 07 04 PM](https://user-images.githubusercontent.com/39919/112736206-450e6580-8f27-11eb-909e-f1c7962903b0.png)

**Comment by Megachile** [comment]
That looks good to me
