### ISSUE TITLE
Add section entries to genus dropdown in ID

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#47]
In two particular genera, there are a few sections that provide more accessible gall info than species level and more useful info than genus level. This is primarily true for oaks and if not for them it wouldn't be worth thinking about. But it would be very useful to filter live, red, and white oaks, and if we're adding that feature we might as well apply it to hickories as well. I think it would be totally acceptable to just add subgenera into the "genus" dropdown menu, so eg instead of 

Pyrus
Quercus
Rhamnus

you'd see

Pyrus
Quercus (all)
Quercus (lobatae)
Quercus (quercus)
Quercus (virentes)
Quercus (protobalanus)
Rhamnus

This seems straightforward enough on the user end, I'm just not sure how feasible it would be on the database side. 

Alternatively, we could have an additional box appear after the user selects either a specific oak species or oak at the genus level, suggesting that if they are not finding what they're looking for or are overwhelmed, they can specify the section (and this would be a good place to give info on how to do that).

**Comment by jeffdc** [comment]
Will we want the ability to maintain these Sections via the admin UI or are they static enough that we will not need that?

**Comment by Megachile** [comment]
I think they should be pretty static--I only know of the ones on oak and hickory and those are not likely to change. The only thing that occurs to me is that we might need to add more oak species and map them to their section at some point, since there are a lot of oak species and we may miss some for whatever reason.

**Comment by jeffdc** [comment]
@Megachile Looking at this more I believe that we will need an admin screen for this. My current plan is to add the database structure to support this, modify code etc, so that it works and then manually add the Sections for the Oaks that are already in the database so that we have some data. Then as a separate chunk of work we can work on an admin screen.

**Comment by Megachile** [comment]
Makes sense to me.
