### ISSUE TITLE
Allow host association at the genus level

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#50]
Some gallformer species are associated with hosts only at the genus level even in the literature. This is not an optimal situation since it's likely that the gallformer is in fact only found on a subset of species in the genus, but since that subset is not known, and sometimes the original host was not named to species, this is the best we can do. But the current mapping page does not permit it, so you'd have to manually associate every species in the genus. (Once we figure out how to add sections to the "genus" list those should be mappable as well. Eg Polystepha galls occur on red oaks but we have no good info on which red oaks).

**Comment by jeffdc** [comment]
What I think we should do is allow choosing a genus in the mapping page, but under the hood just map it to every species in that genus. In other words, keep the association between host and gall at the species level.

**Comment by jeffdc** [comment]
Looking at this more it is not clear what the behavior should actually be here. If we map like I suggested in my previous comment then the Source, Description, and Link will be applied to all Species of that Genus. Is this what we want? It only really makes sense for Galls I would think not Hosts. Currently that page handles mapping of sources for both Galls and Hosts.

**Comment by Megachile** [comment]
Mapping the gall directly to host species under the hood seems like exactly how it should work. Like I said, you could do it manually but it'd be a pain, and also our list of species might not be complete yet, so if we just map to ever member of the down once, then add a new member of that genus later, the relationship should be mapped but wouldn't be. So it would need to update somehow? 

I don't follow the second comment. How are Sources, Descriptions, or Links directly mapped to Hosts at all?

**Comment by jeffdc** [comment]
Oh man my bad. I did not read carefully and got in my head that we are talking about Species-Source mappings not Gall-Host mappings. So in other words. Ignore my 2nd comment.

**Comment by Megachile** [comment]
I think we should add a note on the Add Gallformers page that points users to the Map Galls and Hosts page for this; I just tried to map a new gall to a genus and had to remember that I need to add one host first, then go to the other tool--not something that would be clear to another user.
