### ISSUE TITLE
Sort Further Information by date published

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#51]
The Further Information section containing the list of sources, corresponding to descriptions, should be by default sorted by date published IMO. Sorting by author name is also useful, so maybe the ideal way to handle it would be to let the user choose, sort by author, by date, A-Z or Z-A etc.

**Comment by gschare** [comment]
Would it be better to have a React Bootstrap table with column-based sorting, or to preserve the list look and have buttons to change the order?

**Comment by jeffdc** [comment]
I think that we want to only show the citation so a table will not work. If we switch over to a table then we will have to break things out into columns (i.e., not show the citation). Currently there are already 2 click mechanics with that list:

- Click on text of citation takes you to the source page
- Click on the white space around the text and it selects the source and displays the related description

This is not the greatest set of interactions. The first is fine, but the second is hard to discover. Possibly as part of this overall effort we think about how to fox this.

Also #55 is related to this and can probably be fixed at the same time.

**Comment by Megachile** [comment]
It took me a bit of getting used to to figure out those clicks for sure, although it's not *that* unintuitive. My initial assumption was that clicking the white space wouldn't do anything and the link would do what the white space does now. I wonder if it would make more sense to move the link to the source entry to the end of the citation, in one of those little link arrows maybe (big enough or off to the side so it's not annoying to click on it rather than the white space), to make it clearer that it will open a new window etc, and leave the actual text of the citation as not a link at all? And maybe add a > or something to the white space of the selected source, further emphasizing that it has been selected? Idk if these are good ideas, just spitballing. 

I also think that making sure each gall has a default that loads when you open the page (as #55 would achieve) would help make it unambiguous that the "further info" section contains information that can be accessed from within that page.
