### ISSUE TITLE
How to handle phenology

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#56]
In a few cases, the timing of a gall's occurrence is a very useful ID clue. That makes me think it would be smart to collect any available phenology reports when we pull in sources, and I made a column for it in Airtable, thinking we might at some point want to make a filter with it, so having that info separately would be smart planning.

 But at the moment I lean toward leaving it in the description, available for those who need it but not filterable. A filter implies too much certainty. Too many galls can be found in dried or distorted form months after their appearance; phenology differs substantially by region, so we'd need relatively wide windows to account for users in different places; and phenology data from older sources may not be accurate anymore due to climate change or simply incomplete. In the same spirit as #39, I don't want to give users the impression we can exclude a possible species when we really just lack info. 

At the moment, I would say that the cases where phenology is a strong ID trait are rare enough that we can just put those in notes on the relevant species. Otherwise, it could be a useful marginal clue to make a case between a few similar candidates, but at that point users will already need to be carefully reading the description text anyway. 

Thoughts?

**Comment by madeleineclaire** [comment]
You make a ton of great points. 

The galls can linger in varying states much beyond the seasons in which they were formed. What I had in mind was Callirhytis quercuspomiformis where both the look and the location of the gall are different by generation. 

It would be really cool if there was a way to compile a target species list like on eBird where you can choose your location and a specific date range and get a list of potential galls to look for. You can essentially do the same with iNat, but I find it to be a lot clunkier of a route than the simple checklist eBird produces. If you already have the phenology and regional data available, how difficult would something like that be? I see you are also tracking the rarity of certain species. That could definitely help drive interest in the community seeking them out and then posting observations on iNat and help compile more data around something so incredibly accessible and understudied.

**Comment by jeffdc** [comment]
I agree that putting too much certainty into phenology is not a good idea given the durability of many galls. Further some of the phenology is directly tied to the phenology of the host, e.g. a catkin gall is unlikely to be around in the fall/winter so "location" can in itself be an indicator of phenology.

@madeleineclaire your idea is quite interesting.  I have been very focused on the cataloging and ID side and have not given much thought to how to engage others but this idea seems very interesting. One thing that I want to stay away from for the foreseeable future (i.e., unless/until there is some kind of financial backing) is having user accounts. I do not think that this would stop us from implementing something like @madeleineclaire suggests however.

**Comment by Megachile** [comment]
To answer @madeleineclaire 's point, once we solve #44, the two alternate generations of A q. pomiformis will appear as two distinct galls in search results corresponding to their respective traits. If it's in a different location then it will come up when that location is selected, etc.

**Comment by Megachile** [comment]
I just recently discovered that the Weld book has a section containing lists of all galls sorted by plant part, and, for bud galls, season. The digital copy Charley gave me was missing lots of sections and I still haven't explored the whole book yet. Which is a problem because Weld hides unique info everywhere! Many of his bud gall entries list their season but some do not, so it's nice to have a comprehensive sorted list. 

https://www.biodiversitylibrary.org/item/273718#page/102/mode/1up

Anyway, it's making me come around on the idea of a very broad seasonal checkbox: spring, summer, fall, winter. That should cover variation in range and host and climate change etc, as opposed to using specific months. I said above that it was fine to just look at this info in the entries, but now I find myself wanting to be able to filter by it. We'd just have to put a tooltip that specifies that this only applies to when the gall is fresh, don't use it if the gall looks dried out or old, etc. Thoughts?

**Comment by madeleineclaire** [comment]
I like it and think it would be helpful. Season of formation. I'm all for it as a filter as well. That would come in very handy about now.

**Comment by jeffdc** [comment]
I think that this has potential to confuse people as well as to help. The confusion will come from at least two things:

- the user having to decide, is that gall old or new?
- some species take > 1 year to develop after forming, so will span many seasons, including multiples of the same seasons

It is a complex problem for sure. I am fine adding this stuff but we do need to make sure that we do not make it too easy to eliminate galls from search results simply because of misunderstanding or ignorance of the complexities of phenology.

**Comment by Megachile** [comment]
I wonder if those concerns could be alleviated somewhat by hiding certain filters in an "Advanced" menu as many websites do. I have been pushing for something like that for a while anyway (see #39) and it would allow us greater flexibility in using some of these filters without worrying so much about people stumbling into them without understanding their limits. Ultimately I think season is probably a more robust filter than some of the things we've got in there now.

**Comment by madeleineclaire** [comment]
I love the 'Advanced" menu idea. I also think the pros outweigh the cons on this one. It's a great option for someone using the site in an exploratory way and while I agree that it could cause some confusion here and there for a beginner to galls, it is a great option to help guide someone who has intermediate+ knowledge as an advanced filter option. My vote here: More is more.
