### ISSUE TITLE
Non-gall FAQs Page

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#60]
At some point it would be good to make a page of info on stuff that is frequently misidentified as a gall, eg burls, dodder seeds, Agrobacterium tumors, etc. Notes on leafminers, leaf spot, viruses, etc as well.

**Comment by Megachile** [comment]
Proposal for the ideal long-term way to handle this feature:

1. - [ ] Add a new admin page Non-gall Structures
- [ ]  Title field
- [ ]  Description field
- [ ]  Image uploader with a modal like the existing Add/Edit Images page, with fields for source link, license, license link, creator
2. - [ ]  Page to display entries, similar to the Glossary
- [ ] Title: Structures Commonly Mistaken for Galls
- [ ] Introductory text:  
- [ ] Image gallery, allowing users to scroll through images with titles and descriptions displayed below them and copyright info displayed in an additional "image details" modal as found on the Gall pages now

**Comment by jeffdc** [comment]
This makes sense to me. I will need to a couple of new database tables if this is what we decide we want.
