### ISSUE TITLE
A general introductory guide to Gall ID

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#63]
Should we offer a page that explains galls and gall ID, assuming no prior knowledge to the extent possible, as a way to help orient new users to the tool and its use? This could also point users to things like #60

**Comment by jeffdc** [comment]
I think that this kind of content is great. It is easy to add. If someone provides me the content I can work on getting it styled and formatted. Plain HTML is a good format, or if that is not possible then a Google Doc would work. I would just copy and paste the text and images out of there.

**Comment by Megachile** [comment]
I will draft part of it and send it to you to make sure my html is working.

**Comment by Megachile** [comment]
Unless you mean plain html as in just text?

**Comment by jeffdc** [comment]
Text or HTML is good. If you have specific formatting ideas then HTML is better to convey that.
