### ISSUE TITLE
Autofill Families when genus entered and family known

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#64]
This is a very minor QOL change but is there any reason that, once the database knows that Caryomyia is in Cecidomyiidae, eg, it couldn't/shouldn't autofill the family field when the user enters a new species in that genus?

**Comment by jeffdc** [comment]
It can be done but the relationship is only one-way right now Species knows what Family it is in. A query could be written and an API call from the front-end to the back-end could be made to fetch this data but it is not a simple change.

The other option would be to change the DB structure to map Genera to Families. Currently genera are only stored with a species and are not treated in an special way, they are just text.

This is what the species table looks like:
![Screen Shot 2021-01-29 at 10 20 43 AM](https://user-images.githubusercontent.com/39919/106293188-b5e11c00-621b-11eb-90f6-efb3262b8a80.png)

**Comment by Megachile** [comment]
Okay well like I said, this particular reason is not a big deal. Unless we can think of another reason it would be useful to have Genera mapped to families (there could be some certainly) I'd say we shelve this for now.

**Comment by jeffdc** [comment]
I am going to expand this issue to encompass some other work related to Genus that would require changes that would make this UX issue something that we could then tackle.

**Comment by jeffdc** [comment]
Upon further thought. I am going to create an entirely new issue. I will capture this need in that issue and close this one out.
