### ISSUE TITLE
Display ID filter results as tile gallery

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#65]
The main intent of the filter tool is that users will recognize their gall in a photo, so ideally filter results should display as many images as possible. The square tile arrangement [used in the iNat guides](https://www.inaturalist.org/guides/12068) seems ideal to me but I'm open to other ideas. We could also offer a display mode toggle, given that the list mode is already made.

**Comment by jeffdc** [comment]
I agree that a tiled photo mode will be necessary for the ID result screen. Once I get the images stuff #43 all sorted we will have what we need in place to create this.

I think a toggle between tiled photos and a list is important to have.

**Comment by Megachile** [comment]
One other point relevant to this issue and the broader consideration of image handling is that the current ID results stretches each image into a square, which is not ideal given the importance of shape in recognizing galls. Some of them are distorted beyond the point of legibility.

**Comment by jeffdc** [comment]
Yeah I have noticed that. Should be a reasonably easy fix to change the way the images are rendered. I think that there is probably a CSS property that is incorrectly applied that is stretching them to fill rather than honoring the original aspect ratio.
