### ISSUE TITLE
Image Improvments

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#74]
### User View
- image metadata
- source info
- display with image (as modal) on species pages

### Image Edit
- allow multi-select then edit
- have fields prep-populate from data that exists for a pre-existing source-species-image.

**Comment by jeffdc** [comment]
@megachile Tracking continued image work here.

**Comment by jeffdc** [comment]
@Megachile Thoughts on this for Image metadata display:

Similar to iNat:
![Screen Shot 2021-02-07 at 11 54 21 AM](https://user-images.githubusercontent.com/39919/107153404-609fbb80-693b-11eb-988a-6693148993f9.png)

Then you can click to get the license text:
![Screen Shot 2021-02-07 at 11 55 58 AM](https://user-images.githubusercontent.com/39919/107153415-79a86c80-693b-11eb-8887-3328aaf1bbdc.png)

And then click on the other button to get this modal:
![Screen Shot 2021-02-07 at 11 56 32 AM](https://user-images.githubusercontent.com/39919/107153425-90e75a00-693b-11eb-89d4-abb53d1def01.png)

with an alternate form for an external source:
![Screen Shot 2021-02-07 at 11 56 41 AM](https://user-images.githubusercontent.com/39919/107153437-993f9500-693b-11eb-9e30-012330e1e4ad.png)

**Comment by Megachile** [comment]
Looks good to me

**Comment by jeffdc** [comment]
I have the display stuff working. The multi-edit stuff is not as easy as I thought it would be. It will require a re-think of the UI. Issues that need thinking about for multi-edit:

- if multiple selections already have values that conflict what to display in the edit screen?
- need to indicate that multiple images are selected and not show just one on the edit screen
- uploader can never change so showing that one the edit screen with multiple selections makes not sense
- only one can be default so that would need to be not editable for multiple selections

Maybe as alternative we do this (I think it solves the original issue):

- Provide a Copy to other button
- When clicked it will prompt the user to select the source image to copy from
- Once the source image is selected the user will be prompted to check the target images using the checkboxes in the table
- If all are selected (I added a new (de)select all checkbox in the header) then it will be smart enough to allow this
- once selections are made a Copy button is shown that the User will click to trigger the copy

This gives an overall workflow of something like:

- Upload images
- Edit one with details
- Use new copy functionality to copy to all other relevant uploaded images

Does this work @Megachile?

**Comment by Megachile** [comment]
That sounds like a reasonable solution to me, especially if most of the fields are prepopulated.

**Comment by Megachile** [comment]
This is working well enough for me to start adding images in earnest, although it does seem to have a bit of a bug. After you close the modal to fill in one image metadata, the site doesn't recognize that you've checked that box for "Copy One to Others." But it works fine if I reload the page so not a huge issue.
