### ISSUE TITLE
Filter items to add

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#75]
Location
- [x] leaf edge

Texture
- [x] erineum

Alignment (ps this is spelled wrong on the ID page rn)
- [x] leaning

Color
- [x] green

**Comment by jeffdc** [comment]
I missed the misspelling of Alignment. Will get it with the next deployment.

**Comment by Megachile** [comment]
I'm seeing all of these except Leaning in Alignment.

**Comment by jeffdc** [comment]
Hmmm, I guess I missed Alignment entirely. Oops. Will get it fixed with next update as well.

**Comment by jeffdc** [comment]
Ahhh. I see, you added the Alignment stuff after I had already prepped the migration script. At least I know I am not losing it!

**Comment by Megachile** [comment]
Here's a new set to add:

Color:
black
purple
tan

Alignment: 
leaning

**Comment by jeffdc** [comment]
Should be good to go now.
