### ISSUE TITLE
Undescribed gall submission form

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#76]
In the notes presented to users along with search results discussing the possibility that their gall does not appear (see comments of #39), we should link to a submission form that would allow them to make us aware of undescribed galls so we can document them and add them to the database. IMO the best way to handle this would be to suggest they either link their iNat observation or create an iNat observation if they haven't already. There's no real reason we need them to duplicate really any of that info for us. But I'm open to alternative views.

**Comment by jeffdc** [comment]
I propose that for now (mainly to prevent having to harvest and store user email addresses*) we build a Google Form or equivalent for this.

* Once we ask for and store a user's email address we will need a Privacy Policy as well as GDPR/CCPA/... policies. It is all rather stupid and a sign of what a sad state the modern internet is in.

**Comment by Megachile** [comment]
A Google Form should be fine, I don't know if it really matters where we host it, just what we ask.

**Comment by Megachile** [comment]
On a related note, it occurred to me that for galls that lack any images, we could put a note saying something like "If you have a picture of this gall and are willing to allow us to use it, please contact us here"

**Comment by jeffdc** [comment]
That is a good idea. We need a generic "contact us" form I think. We can direct people to that until we get something more specific. What we do not have, yet, is a general email inbox. We have the domain so we could setup up email on it but it will cost $.

**Comment by Megachile** [comment]
I made us a gmail account, gallformers@gmail.com

**Comment by Megachile** [comment]
For the time being we'll just use text and link to that email address.
