### ISSUE TITLE
All trait fields for galls should be multiselect

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#77]
Edit: The color, walls, cells, alignment, and shape fields should be multiselect fields like Texture is currently; they are all (with the exception maybe of walls and cells but still best to just change those too unless there's a good reason not to?) traits that can take more than one value. 

Original: This is not a priority for me at the moment, but the color, walls, cells, alignment, and shape fields in the admin Add Gallformers page are not working at the moment. They only let you select one option, and there's no way to add more after you've done that. Texture, Location, and Host are working fine though.

**Comment by jeffdc** [comment]
Those fields are not designed to be multiselect, only texture and location currently support that.

**Comment by Megachile** [comment]
Oh okay, changed to reflect that. Was there a reason you did it that way in the first place?

**Comment by jeffdc** [comment]
I do not remember at this point. I am guessing I decided it did not make sense to assign multiples of those.

**Comment by jeffdc** [comment]
As part of the bug fix for #83 I am going to go ahead and make this change as well. Might take a bit longer as a result. To be clear I am going to make:

- Walls
- Cells
- Alignment
- Color
- Shape

all multi-select.

Abundance, which is a property of a species (not just gall so it is also present on hosts) will NOT be multiselect.

**Comment by jeffdc** [comment]
Given that I am already in the same code it may make sense for me to tackle the detachable issue as well. #40 
CC/ @ahiatt14

**Comment by madeleineclaire** [comment]
Hey - quick question here. Did a search and figured this was as good a place as any to ask...

The Location(s) filter on ID Galls. I can tell by the (s) at the end that this is intended to be multi-select, but I'm wondering if it should be. As one of the two key options for filtering galls, this seems like the easiest place to make a mistake. I didn't realize it was multi-select when I was playing around. I was trying to see what I could get to come up for Q. berberidifolia. I was going through each of the areas I recognized as having known galls associated with them and realized that each time I was selecting a location it was adding to the filter. If I were looking for a stem gall but also had previously selected petiole and had not cleared it, would it be looking for a gall that would be set up as both occurring on the stem and the petiole or either on the stem or the petiole (show galls for both options)? If I'm a beginner trying to figure out what a gall is, what would be the value of the multi-select in this field? 

If it's looking for something that would occur on BOTH I have selected, this may be problematic in the same ways we were concerned season may be problematic. If it would look for galls with either of them associated, it could be a huge bonus. For example, if the location of a leaf gall was difficult to distinguish based on size/cluster/whatever, I could select all the leaf options and in the process catch the one I'm looking for. One that comes to mind is the Two-Horned Gall ( Dryocosmus dubiosus) where you can find them along the leaf midrib as well as the leaf veins. Sometimes multiple galls on the same leaf in both locations. 

This gall isn't yet in the database and I was thinking about using it as my first entry so I can play around with it.

**Comment by Megachile** [comment]
This is something I've considered before and, while we could definitely change it following discussion, it is the way it is now for a reason. There are observations where the same gall clearly occurs on multiple parts of the plant. See [eg this one](https://www.inaturalist.org/observations/40986886), where selecting "upper leaf," "leaf midrib," "petiole," and "stem" could help narrow things down. 

I can see the logic of your proposal too, though, especially since our Tips page lists several cases where Location is ambiguous (bud v stem, between v on veins, acorn v bud, midrib v veins) and at the moment the only way to handle that is to search them sequentially. 

One theoretical possibility would be to add a toggle so users can choose whether to use these terms exlusively or inclusively. Not sure if that would cause more confusion than it prevents or would be annoying to implement though.

As for the leaf midrib/veins thing in particular, IMO, any gall tagged "leaf veins" should also be tagged "leaf midrib" because it might appear only on the midrib. Possible some galls are not tagged accordingly, though.

**Comment by madeleineclaire** [comment]
So if I have a gall tagged in the database with leaf veins and leaf midrib and as I user I go to 'ID Gall' and I select leaf vein, leaf midrib, and leaf edge in my search filters, would in include the gall or exclude the gall?

**Comment by madeleineclaire** [comment]
If it's inclusive in that if i have 3 filters selected it presents me with all galls in the database tagged with any of the 3 filters, I think it'll be fine. If it is limiting and required that all 3 of the selected options be true for any single gall, it may cause false negatives. That's really the driver behind my inquiry.

**Comment by Megachile** [comment]
It would exclude it because it doesn't have leaf edge tagged.
