### ISSUE TITLE
Add Note & Links to Gall-Host Mapping Page That Both Host and Gall must Exisit Before Mapping

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#78]
I think we should add a note on the Add Gallformers page that points users to the Map Galls and Hosts page for this; I just tried to map a new gall to a genus and had to remember that I need to add one host first, then go to the other tool--not something that would be clear to another user.

_Originally posted by @Megachile in https://github.com/jeffdc/gallformers/issues/50#issuecomment-775565511_

**Comment by jeffdc** [comment]
Fixed with https://github.com/jeffdc/gallformers/commit/8aae2b4f8adb3e69930709659d17c240c504056d

**Comment by Megachile** [comment]
This is good but I was actually concerned about the other end, the Add/Edit Gallformers page. Can we add a similar note there? Something like "To associate a gall with all plants in a genus, add one species here first, then go to "Gall-Host Mappings."

**Comment by jeffdc** [comment]
Oops, I misunderstood. Will add.
