### ISSUE TITLE
Sometimes Add/Edit Gallformers page clears fields on Submit but doesn't Submit data

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#83]
Sometimes when I complete edits or the details of a new gall in the Add/Edit Gallformers page, I'll click submit and the fields clear but it doesn't take me to the updated/created page and the data doesn't seem to be added if I search for that gall. This happens apparently at random and I've just been dealing with it, but right now it's happening stubbornly with a new gall I just made, Belonocnema kinseyi, which now gives the same result no matter how often I refresh the page. Adding other galls does work, though. No idea what the pattern is here. 

ETA: okay, I narrowed it down a lot. It works if I want to add or remove a value from the Location or host multiselect, or change its detachable status, or if I add or replace a value in Shape, Texture, or Walls. but not if I want to remove a value in Shape, Texture, or Walls without replacing it. So I suppose if those fields are changed to multiselect as in #77 this might just disappear?

**Comment by jeffdc** [comment]
I see the bug and will fix it. I have a bunch of other small fixes and changes and will get them deployed today.

**Comment by Megachile** [comment]
I can't reproduce this at the moment so I'm going to close it; if the issue comes up again in a form I'll make a new issue.

**Comment by jeffdc** [comment]
All of the other changes I made as part of #85 should have fixed this as well. I forgot to attach it.
