### ISSUE TITLE
Direct link to images not presented

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#92]
The "Edit image details" modal allows admin users to provide a "Direct link to image in publication" but this link isn't displayed anywhere on the gall page. I can recover this link easily as an admin with the edit button, but for non-admin users this convenience is not available.

**Comment by Megachile** [comment]
These are gone in the current photo viewer afaict.

**Comment by jeffdc** [comment]
Oops, looks like I forgot to add this back. WIll fix it.
