### ISSUE TITLE
Allow Dashes in Species Names

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#93]
Also tweak image compression  quality from 90 to 100 and add XL size.

_Originally posted by @Megachile in https://github.com/jeffdc/gallformers/issues/45#issuecomment-792988257_

**Comment by Megachile** [comment]
Will this deployment also include the line-break fix for Source entries?

**Comment by jeffdc** [comment]
Yes it will. I will get it deployed tomorrow.
