### ISSUE TITLE
Make source author/date easier to search/see

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#98]
As we accumulate sources, the majority of the ones we'll be consulting in a given group will already be added. But at the moment, it's fairly inconvenient to find them. For instance, Weld lists all the original descriptions in Author Year Publication format. But the Add Source page and the full-site search tool both present only titles. So I have to either open all the sources to find which one is from the right author/year, or just start from scratch and then search by the title, both fairly tedious. Even if you're sure a given source is already added but don't remember the title, you have to go through this same process. 

One simple (tho idk how easily implemented) solution would be to have the search results page show the full citation rather than the title for sources. Another solution would be to make the search tool include the year, so you could search "Weld 1944" and find the source that matches that. But iirc the search tool is less easily modified? 

Similarly, in the source-species mapping tool, searching by title can get confusing because so many titles are nearly identical (we have six variants of "New Cynipidae" already). It would be nice to be able to see author/year there as well, to make sure the one you're selecting is the one you want. In this case I'm not sure there's an obvious or simple solution, so open to ideas here, and this may not be something worth addressing.

**Comment by jeffdc** [comment]
Swapping citation for title is easy, even augmenting global search results with citation is easy. Could also add the year.

For the source-species mapping screen, what if we use the citation rather than the title? Or we could show a combination of any of the fields. Since it is  not editable on that screen it is easy to do.

**Comment by Megachile** [comment]
I think swapping citation in both search results and source-species mapping would be great. Not a priority though, just something that would be nice to have.
