### ISSUE TITLE
If a gall has one source, make it the default

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#99]
I just made a new species and added two sources, and it worked there. So the issue might be that it's only working when it can select the oldest of two or more options?

_Originally posted by @Megachile in https://github.com/jeffdc/gallformers/issues/55#issuecomment-799141488_

**Comment by jeffdc** [comment]
Yes this looks like a simple bug that is easy to fix:

This [line](https://github.com/jeffdc/gallformers/blob/267ebc98a1ef64165836a6258d9a481ac9eade39/libs/pages/renderhelpers.tsx#L49) should be changed from:

`if (speciessource && speciessource.length > 1) { `

to:

`if (speciessource && speciessource.length > 0) { `
